/**
 * ============================================================================
 * SHAPE DEFINITIONS — edit this file to change scoring standards
 * ============================================================================
 * HOW TO ADD A NEW SHAPE
 * ----------------------
 * 1. Copy an existing shape block below.
 * 2. Give it a unique `id` (lowercase, no spaces) and a clear `name`.
 * 3. Set `qualityThreshold` (score 0–100 required for "quality hold" time).
 * 4. List `criteria` using the reusable measurement kinds:
 *
 *    joint_angle          → angle at a joint (shoulder–elbow–wrist, etc.)
 *    segment_vs_vertical  → how upright a body line is (0° = vertical)
 *    segment_vs_horizontal→ how level a body line is (0° = horizontal)
 *    point_distance       → how close two landmarks are (feet together)
 *    forward_of           → how far pair[0] is in front of pair[1] (heel→toe facing)
 *    symmetry             → left/right joint angle difference (0° = perfect)
 *    composite_min        → overall = worst of several hidden "_..." criteria
 *
 * 5. For each criterion set:
 *    - target OR targetMin/targetMax
 *    - tolerance  (still scores 100 inside this band)
 *    - falloff    (how quickly score drops outside the band; default 40)
 *    - weight     (relative importance — numbers don't need to sum to 100)
 *    - feedbackLow / feedbackHigh with optional {delta} placeholder
 *
 * Landmark indices are in src/lib/landmarks.ts (LM.LEFT_ELBOW, etc.).
 *
 * HIDDEN HELPERS: criteria whose id starts with "_" are measured but not
 * shown in the score panel. Use them as building blocks for composite_min.
 *
 * ANGLE CHEAT SHEET
 * -----------------
 * Straight elbow / knee / hip line ≈ 165–180°
 * Vertical body line deviation     ≈ 0–15° from vertical
 * Horizontal lever body            ≈ 0–20° from horizontal
 * Feet together distance           ≈ 0–0.08 (normalized frame units)
 */

import { LM } from '../lib/landmarks'
import type { CriterionDef, ShapeDef } from '../types'

/** Shortcut: left elbow angle landmarks */
const L_ELBOW: [number, number, number] = [LM.LEFT_SHOULDER, LM.LEFT_ELBOW, LM.LEFT_WRIST]
const R_ELBOW: [number, number, number] = [LM.RIGHT_SHOULDER, LM.RIGHT_ELBOW, LM.RIGHT_WRIST]
const L_KNEE: [number, number, number] = [LM.LEFT_HIP, LM.LEFT_KNEE, LM.LEFT_ANKLE]
const R_KNEE: [number, number, number] = [LM.RIGHT_HIP, LM.RIGHT_KNEE, LM.RIGHT_ANKLE]
const L_HIP: [number, number, number] = [LM.LEFT_SHOULDER, LM.LEFT_HIP, LM.LEFT_KNEE]
const R_HIP: [number, number, number] = [LM.RIGHT_SHOULDER, LM.RIGHT_HIP, LM.RIGHT_KNEE]
const L_SHOULDER: [number, number, number] = [LM.LEFT_HIP, LM.LEFT_SHOULDER, LM.LEFT_ELBOW]
const R_SHOULDER: [number, number, number] = [LM.RIGHT_HIP, LM.RIGHT_SHOULDER, LM.RIGHT_ELBOW]

/** Back heel FLAT — landing lunge and every lunge arm-position hold. */
const LANDING_HEEL_FLAT: CriterionDef = {
  id: 'heel_flat',
  label: 'Back heel flat',
  kind: 'segment_vs_horizontal',
  segment: [LM.RIGHT_HEEL, LM.RIGHT_FOOT_INDEX],
  target: 0,
  tolerance: 12,
  falloff: 40,
  weight: 14,
  needsView: 'side',
  feedbackHigh: 'Press the back heel flat.',
}

/**
 * Lunges: back leg must actually be straight. Graded from the named back
 * knee (no “better of L/R” fallback) so a mountain climber cannot pass.
 */
const LUNGE_BACK_LEG: CriterionDef = {
  id: 'back_leg',
  label: 'Back leg straight',
  kind: 'joint_angle',
  points: R_KNEE,
  targetMin: 155,
  targetMax: 180,
  tolerance: 10,
  weight: 18,
  feedbackLow: 'Straighten the back leg.',
}

/** Shorter stance than the starting lunge. */
const LANDING_CLOSER_STEP: CriterionDef = {
  id: 'closer_step',
  label: 'Closer than starting lunge',
  kind: 'point_distance',
  pair: [LM.LEFT_ANKLE, LM.RIGHT_ANKLE],
  targetMin: 0.1,
  targetMax: 0.24,
  tolerance: 0.04,
  falloff: 0.22,
  weight: 12,
  feedbackLow: 'Take a small step — still shorter than a starting lunge.',
  feedbackHigh: 'Bring the feet closer — shorter than the starting lunge.',
}

/** Lunges/lever: a long line from the BACK FOOT to the SHOULDERS (not the still). */
const LUNGE_DIAGONAL: CriterionDef = {
  id: 'line_foot_hands',
  label: 'Long line back foot → shoulders',
  kind: 'segment_vs_horizontal',
  segment: [LM.RIGHT_ANKLE, LM.LEFT_SHOULDER],
  targetMin: 8,
  targetMax: 50,
  tolerance: 14,
  falloff: 40,
  weight: 14,
  needsView: 'side',
  feedbackLow: 'Tilt the chest a bit — long line from back foot to shoulders.',
  feedbackHigh: 'Keep a long diagonal from back foot to shoulders — this is not a lever yet.',
}

/**
 * Open shoulders on starting lunge, landing lunge, and lever.
 * 75% is a pass — not a perfect 180°. Graded in writing after the snapshot.
 * Side-on MediaPipe often under-reads arms-by-ears.
 */
const LUNGE_OPEN_SHOULDERS: CriterionDef = {
  id: 'shoulders',
  label: 'Open shoulders',
  kind: 'joint_angle',
  points: L_SHOULDER,
  targetMin: 110,
  targetMax: 180,
  tolerance: 32,
  falloff: 55,
  weight: 16,
  feedbackLow: 'Open shoulders — arms by ears.',
}
const LUNGE_STRAIGHT_BACK: CriterionDef = {
  id: 'straight_back',
  label: 'Straight back (not a C)',
  kind: 'joint_angle',
  points: R_HIP,
  targetMin: 155,
  targetMax: 180,
  tolerance: 10,
  falloff: 40,
  weight: 12,
  feedbackLow: 'Straighten the back — this is a lunge, not a mountain climber C.',
}

/**
 * All shapes available in Shape Lab v1.
 * Handstand is the most complete reference implementation.
 */
export const SHAPES: ShapeDef[] = [
  // ===========================================================================
  // HANDSTAND — most complete example (test this first)
  // Side or slightly oblique camera works best so the body line is visible.
  // ===========================================================================
  {
    id: 'handstand',
    name: 'Handstand',
    description:
      'Fully straight line, ribs in, butt in. Straight elbows, open shoulders, straight knees, pointed toes. Push through the ground and stand tall.',
    bodyPosition:
      'SIDE or 3/4. Hands on the floor. Straight elbows, open shoulders, ears covered. Ribs in, butt in, hips stacked, knees straight, toes pointed. One long vertical line from hands to toes — push through the ground and stand tall. Looking up toward the hands is fine if the ears stay covered. Goal: cover the ears and see the thumbs through the eyebrows. Looking at the wall behind you is only a temporary cue if it straightens the line.',
    category: 'hold',
    qualityThreshold: 70,
    cameraView: 'side',
    tips: [
      'Side or 3/4 view — not face-on. We need to see the body line.',
      'Push through the ground. Stand tall in a straight line.',
      'Ribs in, butt in. Straight elbows, open shoulders, straight knees, pointed toes.',
      'Cover the ears. Seeing the thumbs through the eyebrows is the goal.',
    ],
    coachNotes:
      'Fully straight line with ribs in. The athlete can look up toward the hands as long as the ears are still covered. I commonly tell athletes to look at the wall behind them if that straightens out the line initially, but it is encouraged to cover the ears and see the thumbs through the eyebrows. Straight elbows, open shoulders, ribs in, butt in, straight knees, pointed toes. Pushing through the ground, standing tall in a straight line.',
    criteria: [
      // --- hidden left/right building blocks ---
      {
        id: '_left_elbow',
        label: 'Left elbow',
        kind: 'joint_angle',
        points: L_ELBOW,
        targetMin: 165,
        targetMax: 180,
        tolerance: 5,
        falloff: 35,
        weight: 1,
        feedbackLow: 'Straighten left elbow {delta}° more.',
      },
      {
        id: '_right_elbow',
        label: 'Right elbow',
        kind: 'joint_angle',
        points: R_ELBOW,
        targetMin: 165,
        targetMax: 180,
        tolerance: 5,
        falloff: 35,
        weight: 1,
        feedbackLow: 'Straighten right elbow {delta}° more.',
      },
      {
        id: '_left_knee',
        label: 'Left knee',
        kind: 'joint_angle',
        points: L_KNEE,
        targetMin: 165,
        targetMax: 180,
        tolerance: 5,
        falloff: 35,
        weight: 1,
        feedbackLow: 'Straighten left knee {delta}° more.',
      },
      {
        id: '_right_knee',
        label: 'Right knee',
        kind: 'joint_angle',
        points: R_KNEE,
        targetMin: 165,
        targetMax: 180,
        tolerance: 5,
        falloff: 35,
        weight: 1,
        feedbackLow: 'Straighten right knee {delta}° more.',
      },
      {
        id: '_left_hip',
        label: 'Left hip',
        kind: 'joint_angle',
        points: L_HIP,
        targetMin: 160,
        targetMax: 180,
        tolerance: 8,
        falloff: 40,
        weight: 1,
        feedbackLow: 'Open left hip {delta}° more (reduce pike).',
        feedbackHigh: 'Reduce left hip arch {delta}°.',
      },
      {
        id: '_right_hip',
        label: 'Right hip',
        kind: 'joint_angle',
        points: R_HIP,
        targetMin: 160,
        targetMax: 180,
        tolerance: 8,
        falloff: 40,
        weight: 1,
        feedbackLow: 'Open right hip {delta}° more (reduce pike).',
        feedbackHigh: 'Reduce right hip arch {delta}°.',
      },
      {
        id: '_left_shoulder',
        label: 'Left shoulder',
        kind: 'joint_angle',
        points: L_SHOULDER,
        // Open shoulders in handstand ≈ large hip–shoulder–elbow angle
        targetMin: 150,
        targetMax: 180,
        tolerance: 10,
        falloff: 45,
        weight: 1,
        feedbackLow: 'Open left shoulder {delta}° more (arms by ears).',
      },
      {
        id: '_right_shoulder',
        label: 'Right shoulder',
        kind: 'joint_angle',
        points: R_SHOULDER,
        targetMin: 150,
        targetMax: 180,
        tolerance: 10,
        falloff: 45,
        weight: 1,
        feedbackLow: 'Open right shoulder {delta}° more (arms by ears).',
      },

      // --- visible scored criteria (what the coach sees) ---
      {
        id: 'shoulders',
        label: 'Shoulders',
        kind: 'composite_min',
        of: ['_left_shoulder', '_right_shoulder'],
        tolerance: 0,
        weight: 20,
        feedbackLow: 'Open shoulders {delta}° more.',
      },
      {
        id: 'elbows',
        label: 'Elbows',
        kind: 'composite_min',
        of: ['_left_elbow', '_right_elbow'],
        tolerance: 0,
        weight: 18,
        feedbackLow: 'Straighten elbows {delta}° more.',
      },
      {
        id: 'hips',
        label: 'Ribs in / butt in',
        kind: 'composite_min',
        of: ['_left_hip', '_right_hip'],
        tolerance: 0,
        weight: 18,
        feedbackLow: 'Ribs in — reduce pike.',
        feedbackHigh: 'Butt in — reduce the arch.',
      },
      {
        id: 'knees',
        label: 'Knees',
        kind: 'composite_min',
        of: ['_left_knee', '_right_knee'],
        tolerance: 0,
        weight: 14,
        feedbackLow: 'Straighten knees {delta}° more.',
      },
      {
        id: 'body_line',
        label: 'Body line',
        kind: 'segment_vs_vertical',
        segment: [LM.LEFT_SHOULDER, LM.LEFT_ANKLE],
        target: 0,
        tolerance: 12,
        falloff: 40,
        weight: 16,
        needsView: 'side',
        feedbackHigh: 'Push through the ground — stand tall in a straight line ({delta}° off).',
      },
      {
        id: 'head',
        label: 'Ears covered',
        kind: 'segment_vs_vertical',
        // Looking toward the hands is OK. A huge head poke (wall-stare) is only a light cue.
        segment: [LM.LEFT_SHOULDER, LM.NOSE],
        targetMin: 0,
        targetMax: 48,
        tolerance: 14,
        falloff: 50,
        weight: 4,
        feedbackHigh: 'Cover the ears — see the thumbs through the eyebrows if you can.',
      },
      {
        id: 'feet_together',
        label: 'Feet together',
        kind: 'point_distance',
        pair: [LM.LEFT_ANKLE, LM.RIGHT_ANKLE],
        target: 0,
        tolerance: 0.06,
        falloff: 0.2,
        weight: 6,
        feedbackHigh: 'Squeeze feet together.',
      },
      {
        id: 'toes',
        label: 'Toes pointed',
        kind: 'segment_vs_vertical',
        segment: [LM.LEFT_HEEL, LM.LEFT_FOOT_INDEX],
        target: 0,
        tolerance: 22,
        falloff: 50,
        weight: 6,
        needsView: 'side',
        feedbackHigh: 'Point the toes ({delta}°).',
      },
    ],
  },

  // ===========================================================================
  // STAND CLEAN — tall posture, feet together (task 1)
  // ===========================================================================
  {
    id: 'stand_clean',
    name: 'Stand clean',
    description: 'Tall clean stand: feet together, posture set, body stacked before anything else.',
    bodyPosition:
      'Stand tall. Feet glued (heels and toes). Knees straight. Hips stacked under the ribs. Arms relaxed or by the sides. Head high. This is the “clean” start before any other shape.',
    category: 'static',
    qualityThreshold: 70,
    cameraView: 'any',
    tips: [
      'Any facing is fine.',
      'Feet glued together.',
      'Stand tall through the crown of the head.',
    ],
    criteria: [
      {
        id: 'feet_together',
        label: 'Feet together',
        kind: 'point_distance',
        pair: [LM.LEFT_ANKLE, LM.RIGHT_ANKLE],
        target: 0,
        tolerance: 0.06,
        falloff: 0.18,
        weight: 28,
        feedbackHigh: 'Bring feet together.',
      },
      {
        id: 'knees',
        label: 'Knees straight',
        kind: 'composite_min',
        of: ['_sc_left_knee', '_sc_right_knee'],
        tolerance: 0,
        weight: 22,
        feedbackLow: 'Straighten knees.',
      },
      {
        id: '_sc_left_knee',
        label: 'Left knee',
        kind: 'joint_angle',
        points: L_KNEE,
        targetMin: 165,
        targetMax: 180,
        tolerance: 5,
        falloff: 35,
        weight: 1,
        feedbackLow: 'Straighten left knee.',
      },
      {
        id: '_sc_right_knee',
        label: 'Right knee',
        kind: 'joint_angle',
        points: R_KNEE,
        targetMin: 165,
        targetMax: 180,
        tolerance: 5,
        falloff: 35,
        weight: 1,
        feedbackLow: 'Straighten right knee.',
      },
      {
        id: 'torso',
        label: 'Torso tall',
        kind: 'segment_vs_vertical',
        segment: [LM.LEFT_HIP, LM.LEFT_SHOULDER],
        target: 0,
        tolerance: 10,
        falloff: 35,
        weight: 25,
        feedbackHigh: 'Stand taller — torso {delta}° off vertical.',
      },
      {
        id: 'hips',
        label: 'Hips open',
        kind: 'joint_angle',
        points: L_HIP,
        targetMin: 160,
        targetMax: 180,
        tolerance: 8,
        weight: 15,
        feedbackLow: 'Open hips / stand taller.',
      },
      {
        id: 'head',
        label: 'Chin / head',
        kind: 'segment_vs_vertical',
        segment: [LM.LEFT_SHOULDER, LM.NOSE],
        targetMin: 0,
        targetMax: 30,
        tolerance: 10,
        falloff: 40,
        weight: 10,
        feedbackHigh: 'Lift chin slightly — head {delta}° off.',
      },
    ],
  },

  // ===========================================================================
  // FEET TOGETHER, OPEN SHOULDERS (task 2)
  // Front/3/4: stacked stand, then often pull a passé.
  // ===========================================================================
  {
    id: 'feet_together_open_shoulders',
    name: 'Feet together, open shoulders',
    description:
      'Feet together, straight knees, open hips, ribs in, open shoulders, chin up and neutral, straight elbows, hands reaching to the ceiling.',
    bodyPosition:
      'Feet glued. Knees straight. Hips open. Ribs in (no arch). Shoulders fully open, arms covering the ears, elbows locked, hands reaching to the ceiling. Chin up and neutral — look straight ahead. This is the same long body you take into passé. Standalone: front or 3/4 is easiest to see both arms. In a sequence, stay in profile — you do not need to face the camera.',
    category: 'static',
    qualityThreshold: 70,
    cameraView: 'any',
    tips: [
      'Standalone: front or 3/4 is easiest to see both arms.',
      'In a sequence, stay in profile — do not turn to face the camera.',
      'Feet together, knees straight, hips open, ribs in.',
      'Open shoulders, elbows straight, hands to the ceiling.',
      'Chin up and neutral.',
    ],
    coachNotes:
      'We will often start here before pulling a passé. Keep feet together, straight knees, open hips, ribs in, open shoulders, chin up and neutral, straight elbows, and hands reaching toward the ceiling.',
    criteria: [
      {
        id: 'feet_together',
        label: 'Feet together',
        kind: 'point_distance',
        pair: [LM.LEFT_ANKLE, LM.RIGHT_ANKLE],
        target: 0,
        tolerance: 0.06,
        falloff: 0.18,
        weight: 14,
        feedbackHigh: 'Squeeze feet together.',
      },
      {
        id: 'knees',
        label: 'Knees straight',
        kind: 'composite_min',
        of: ['_ftos_lk', '_ftos_rk'],
        tolerance: 0,
        weight: 16,
        feedbackLow: 'Straighten knees.',
      },
      {
        id: '_ftos_lk',
        label: 'Left knee',
        kind: 'joint_angle',
        points: L_KNEE,
        targetMin: 165,
        targetMax: 180,
        tolerance: 5,
        weight: 1,
        feedbackLow: 'Straighten left knee.',
      },
      {
        id: '_ftos_rk',
        label: 'Right knee',
        kind: 'joint_angle',
        points: R_KNEE,
        targetMin: 165,
        targetMax: 180,
        tolerance: 5,
        weight: 1,
        feedbackLow: 'Straighten right knee.',
      },
      {
        id: 'hips',
        label: 'Hips open',
        kind: 'composite_min',
        of: ['_ftos_lh', '_ftos_rh'],
        tolerance: 0,
        weight: 16,
        feedbackLow: 'Open hips.',
      },
      {
        id: '_ftos_lh',
        label: 'Left hip',
        kind: 'joint_angle',
        points: L_HIP,
        targetMin: 160,
        targetMax: 180,
        tolerance: 8,
        weight: 1,
        feedbackLow: 'Open left hip.',
      },
      {
        id: '_ftos_rh',
        label: 'Right hip',
        kind: 'joint_angle',
        points: R_HIP,
        targetMin: 160,
        targetMax: 180,
        tolerance: 8,
        weight: 1,
        feedbackLow: 'Open right hip.',
      },
      {
        id: 'shoulders',
        label: 'Open shoulders',
        kind: 'composite_min',
        of: ['_ftos_ls', '_ftos_rs'],
        tolerance: 0,
        weight: 22,
        feedbackLow: 'Open shoulders — arms by ears.',
      },
      {
        id: '_ftos_ls',
        label: 'Left shoulder',
        kind: 'joint_angle',
        points: L_SHOULDER,
        targetMin: 150,
        targetMax: 180,
        tolerance: 10,
        weight: 1,
        feedbackLow: 'Open left shoulder.',
      },
      {
        id: '_ftos_rs',
        label: 'Right shoulder',
        kind: 'joint_angle',
        points: R_SHOULDER,
        targetMin: 150,
        targetMax: 180,
        tolerance: 10,
        weight: 1,
        feedbackLow: 'Open right shoulder.',
      },
      {
        id: 'elbows',
        label: 'Elbows straight',
        kind: 'composite_min',
        of: ['_ftos_le', '_ftos_re'],
        tolerance: 0,
        weight: 18,
        feedbackLow: 'Straighten elbows.',
      },
      {
        id: '_ftos_le',
        label: 'Left elbow',
        kind: 'joint_angle',
        points: L_ELBOW,
        targetMin: 165,
        targetMax: 180,
        tolerance: 5,
        weight: 1,
        feedbackLow: 'Straighten left elbow.',
      },
      {
        id: '_ftos_re',
        label: 'Right elbow',
        kind: 'joint_angle',
        points: R_ELBOW,
        targetMin: 165,
        targetMax: 180,
        tolerance: 5,
        weight: 1,
        feedbackLow: 'Straighten right elbow.',
      },
      {
        id: 'hands_up',
        label: 'Hands to ceiling',
        kind: 'segment_vs_vertical',
        segment: [LM.LEFT_SHOULDER, LM.LEFT_WRIST],
        target: 0,
        tolerance: 15,
        falloff: 40,
        weight: 12,
        feedbackHigh: 'Reach hands straight up to the ceiling ({delta}°).',
      },
      {
        id: 'symmetry',
        label: 'Left / right even',
        kind: 'symmetry',
        leftPoints: L_SHOULDER,
        rightPoints: R_SHOULDER,
        target: 0,
        tolerance: 12,
        falloff: 40,
        weight: 8,
        feedbackHigh: 'Even the arms — left/right differ by {delta}°.',
      },
      {
        id: 'ribs_in',
        label: 'Ribs in / torso stacked',
        kind: 'segment_vs_vertical',
        segment: [LM.LEFT_HIP, LM.LEFT_SHOULDER],
        target: 0,
        tolerance: 10,
        falloff: 35,
        weight: 10,
        feedbackHigh: 'Ribs in — stand stacked, no arch ({delta}°).',
      },
      {
        id: 'chin',
        label: 'Chin up, neutral',
        kind: 'segment_vs_vertical',
        segment: [LM.LEFT_SHOULDER, LM.NOSE],
        targetMin: 0,
        targetMax: 30,
        tolerance: 10,
        falloff: 40,
        weight: 8,
        feedbackHigh: 'Chin up and neutral — look straight ahead ({delta}°).',
      },
    ],
  },

  // ===========================================================================
  // LUNGE (generic coach shape — upright torso; kept for sequences.ts)
  // ===========================================================================
  {
    id: 'lunge',
    name: 'Lunge',
    description: 'Lunge with front knee bent, back leg long, torso upright, arms by ears.',
    category: 'static',
    qualityThreshold: 65,
    tips: ['Keep hips square and torso tall.', 'Arms cover the ears.'],
    criteria: [
      {
        id: '_front_knee',
        label: 'Front knee',
        kind: 'joint_angle',
        points: L_KNEE,
        targetMin: 80,
        targetMax: 110,
        tolerance: 10,
        falloff: 40,
        weight: 1,
        feedbackLow: 'Bend front knee more ({delta}°).',
        feedbackHigh: 'Ease front knee bend ({delta}°).',
      },
      {
        id: '_back_knee',
        label: 'Back knee',
        kind: 'joint_angle',
        points: R_KNEE,
        targetMin: 150,
        targetMax: 180,
        tolerance: 10,
        falloff: 40,
        weight: 1,
        feedbackLow: 'Straighten back leg {delta}° more.',
      },
      {
        id: 'front_knee',
        label: 'Front knee',
        kind: 'joint_angle',
        points: L_KNEE,
        targetMin: 80,
        targetMax: 110,
        tolerance: 10,
        weight: 22,
        feedbackLow: 'Bend front knee more ({delta}°).',
        feedbackHigh: 'Ease front knee bend ({delta}°).',
      },
      {
        id: 'back_leg',
        label: 'Back leg',
        kind: 'joint_angle',
        points: R_KNEE,
        targetMin: 150,
        targetMax: 180,
        tolerance: 10,
        weight: 20,
        feedbackLow: 'Straighten back leg {delta}° more.',
      },
      {
        id: 'torso',
        label: 'Torso upright',
        kind: 'segment_vs_vertical',
        segment: [LM.LEFT_HIP, LM.LEFT_SHOULDER],
        target: 0,
        tolerance: 15,
        falloff: 40,
        weight: 20,
        feedbackHigh: 'Stand taller — torso is {delta}° off vertical.',
      },
      {
        id: 'shoulders_open',
        label: 'Arms by ears',
        kind: 'joint_angle',
        points: L_SHOULDER,
        targetMin: 140,
        targetMax: 180,
        tolerance: 10,
        weight: 18,
        feedbackLow: 'Cover ears with arms — open shoulders {delta}°.',
      },
      {
        id: 'elbows',
        label: 'Elbows straight',
        kind: 'joint_angle',
        points: L_ELBOW,
        targetMin: 160,
        targetMax: 180,
        tolerance: 8,
        weight: 12,
        feedbackLow: 'Straighten elbows {delta}°.',
      },
      {
        id: 'hips_square',
        label: 'Hip square (symmetry)',
        kind: 'symmetry',
        leftPoints: L_HIP,
        rightPoints: R_HIP,
        target: 0,
        tolerance: 20,
        falloff: 50,
        weight: 8,
        feedbackHigh: 'Square the hips — left/right differ by {delta}°.',
      },
    ],
  },

  // ===========================================================================
  // STARTING LUNGE — heel UP, straight back leg, straight back, open shoulders (task 5)
  // Fall forward from passé. Usual cartwheel start (or mountain climber).
  // ===========================================================================
  {
    id: 'lunge_start',
    name: 'Starting lunge with open shoulders',
    description:
      'Starting lunge: back heel UP, back leg straight, back straight, shoulders open. Longer stance than the landing lunge. Fall here from passé; usual cartwheel start.',
    bodyPosition:
      'SIDE VIEW. Fall forward from passé into this lunge. Front knee bent. Back leg long and STRAIGHT. Back heel UP on the ball of the foot — this is the only lunge that requires heel up. Back stays STRAIGHT (not a C). Shoulders OPEN, arms by the ears, one diagonal from the back foot through the body to the hands. Longer stance than a landing lunge. This is not a mountain climber.',
    category: 'static',
    qualityThreshold: 75,
    cameraView: 'side',
    stanceAware: true,
    tips: [
      'SIDE VIEW — stand in profile. Do not face the camera.',
      'Back heel up. Back leg straight. Back straight. Shoulders open.',
      'Longer stance than the landing lunge.',
      'Not a mountain climber — do not bend the back knee or round into a C.',
    ],
    coachNotes:
      'Land here from falling forward on a passé. Cartwheels usually start from this shape or from a mountain climber. Know the difference: on lunges the back leg is straight, the back is straight, and the shoulders are open. A mountain climber is a C plus one medium step (or a lunge with the back knee bent and a C upper body). We never finish a skill in a mountain climber.',
    criteria: [
      {
        id: 'front_knee',
        label: 'Front knee',
        kind: 'joint_angle',
        points: L_KNEE,
        targetMin: 80,
        targetMax: 115,
        tolerance: 12,
        weight: 16,
        feedbackLow: 'Bend front knee more.',
        feedbackHigh: 'Ease front knee bend.',
      },
      LUNGE_BACK_LEG,
      {
        id: 'heel_up',
        label: 'Back heel up',
        // Heel raised off the floor: heel→toe segment tips up vs horizontal
        kind: 'segment_vs_horizontal',
        segment: [LM.RIGHT_FOOT_INDEX, LM.RIGHT_HEEL],
        targetMin: 15,
        targetMax: 55,
        tolerance: 10,
        falloff: 45,
        weight: 14,
        needsView: 'side',
        feedbackLow: 'Lift the back heel — stay on the ball of the foot.',
        feedbackHigh: 'Keep heel up but stable.',
      },
      {
        id: 'longer_step',
        label: 'Longer step than landing',
        kind: 'point_distance',
        pair: [LM.LEFT_ANKLE, LM.RIGHT_ANKLE],
        targetMin: 0.22,
        targetMax: 0.5,
        tolerance: 0.05,
        falloff: 0.25,
        weight: 10,
        feedbackLow: 'Take a longer step — bigger than the landing lunge.',
        feedbackHigh: 'A bit smaller — still longer than the landing lunge.',
      },
      LUNGE_DIAGONAL,
      LUNGE_OPEN_SHOULDERS,
      {
        id: 'elbows',
        label: 'Elbows straight',
        kind: 'joint_angle',
        points: L_ELBOW,
        targetMin: 160,
        targetMax: 180,
        tolerance: 8,
        weight: 8,
        feedbackLow: 'Straighten elbows.',
      },
      LUNGE_STRAIGHT_BACK,
    ],
  },

  // ===========================================================================
  // LANDING LUNGE — heel FLAT, shorter stance than start (task 9)
  // Finish for usual cartwheels (cartwheel step-ins / RO prep land in zombie)
  // and every lunge → lever → HS → lunge.
  // ===========================================================================
  {
    id: 'lunge_land',
    name: 'Landing lunge',
    description:
      'Landing lunge: shorter stance than the start, back heel FLAT, back leg straight, one line from back heel through the body to the hands.',
    bodyPosition:
      'SIDE VIEW. Front knee bent, back leg long and STRAIGHT. Back stays STRAIGHT (not a C). Shoulders OPEN. Back HEEL FLAT on the floor — do not roll in on the arch. Feet closer together than a starting lunge. One diagonal from the back heel through the hips and shoulders to the hands. Either leg forward unless the task specifies a side.',
    category: 'static',
    qualityThreshold: 75,
    cameraView: 'side',
    stanceAware: true,
    tips: [
      'SIDE VIEW required.',
      'Shorter stance than the starting lunge.',
      'Press the back heel flat — no rolling in on the arch.',
      'Back leg straight, back straight, shoulders open — not a mountain climber.',
    ],
    coachNotes:
      'Usual cartwheels finish in this landing lunge. Cartwheel step-ins (the round-off prep) finish in a zombie instead — train that landing before round-offs. Every lunge → lever → handstand → lunge sequence finishes here. All lunge arm-position drills use this same stance: back heel flat, feet closer than a starting lunge.',
    criteria: [
      {
        id: 'front_knee',
        label: 'Front knee',
        kind: 'joint_angle',
        points: L_KNEE,
        targetMin: 85,
        targetMax: 125,
        tolerance: 12,
        weight: 16,
        feedbackLow: 'Bend front knee more.',
        feedbackHigh: 'Ease front knee bend.',
      },
      LUNGE_BACK_LEG,
      LANDING_HEEL_FLAT,
      LANDING_CLOSER_STEP,
      LUNGE_DIAGONAL,
      { ...LUNGE_OPEN_SHOULDERS, weight: 16 },
      {
        id: 'elbows',
        label: 'Elbows straight',
        kind: 'joint_angle',
        points: L_ELBOW,
        targetMin: 160,
        targetMax: 180,
        tolerance: 8,
        weight: 8,
        feedbackLow: 'Straighten elbows.',
      },
      LUNGE_STRAIGHT_BACK,
    ],
  },

  // ===========================================================================
  // LEVER — slight front-knee bend, chest parallel, line back foot → hands (task 7)
  // ===========================================================================
  {
    id: 'lever',
    name: 'Lever',
    description:
      'Front knee slightly bent. Chest tilts until parallel with the ground. Back leg lifts so one straight line from back foot to hands sits parallel to the floor. Open shoulders.',
    bodyPosition:
      'SIDE VIEW. Weight on the front/support foot with a SLIGHT bend in that knee (not locked, not a deep squat). Chest tilts forward until it is parallel with the ground. Back leg lifts and stays long so one straight line runs from the back foot through the body to the hands — that whole line parallel with the floor. Shoulders OPEN, arms by the ears. Either leg can be the support leg.',
    category: 'hold',
    qualityThreshold: 75,
    cameraView: 'side',
    stanceAware: true,
    tips: [
      'SIDE VIEW required.',
      'Slight bend in the front knee — not locked, not sitting.',
      'Tilt the chest until it is parallel with the floor.',
      'Lift the back leg: one line back foot → hands, parallel to the ground.',
      'Open shoulders — arms by the ears.',
    ],
    coachNotes:
      'Front knee should be slightly bent. Chest tilts forward until parallel with the ground. The back leg lifts up to keep a straight line from back foot to hands, with that whole line parallel with the ground. Open shoulders.',
    criteria: [
      {
        id: 'front_knee',
        label: 'Front knee slightly bent',
        kind: 'joint_angle',
        points: L_KNEE,
        targetMin: 145,
        targetMax: 172,
        tolerance: 8,
        falloff: 40,
        weight: 18,
        feedbackLow: 'Don’t sit so deep — only a slight bend in the front knee.',
        feedbackHigh: 'Soften the front knee — not locked straight.',
      },
      {
        id: 'chest_parallel',
        label: 'Chest parallel',
        kind: 'segment_vs_horizontal',
        segment: [LM.LEFT_HIP, LM.LEFT_SHOULDER],
        target: 0,
        tolerance: 15,
        falloff: 40,
        weight: 24,
        needsView: 'side',
        feedbackHigh: 'Tilt chest parallel to the ground ({delta}°).',
      },
      {
        id: 'line_foot_hands',
        label: 'Line back foot → shoulders',
        kind: 'segment_vs_horizontal',
        segment: [LM.RIGHT_ANKLE, LM.LEFT_SHOULDER],
        target: 0,
        tolerance: 18,
        falloff: 45,
        weight: 22,
        needsView: 'side',
        feedbackHigh: 'Lift the back leg — one line from back foot to shoulders, parallel to the ground.',
      },
      {
        ...LUNGE_OPEN_SHOULDERS,
        feedbackLow: 'Open shoulders — arms by ears.',
      },
      {
        id: 'elbows',
        label: 'Elbows straight',
        kind: 'joint_angle',
        points: L_ELBOW,
        targetMin: 160,
        targetMax: 180,
        tolerance: 8,
        weight: 8,
        feedbackLow: 'Straighten elbows.',
      },
      {
        id: 'back_leg',
        label: 'Back leg long',
        kind: 'joint_angle',
        points: R_KNEE,
        targetMin: 155,
        targetMax: 180,
        tolerance: 10,
        weight: 14,
        feedbackLow: 'Lengthen / straighten the back leg.',
      },
    ],
  },

  // ===========================================================================
  // MOUNTAIN CLIMBER — C + medium step, both knees bent (task 15)
  // Pass-through entry only. Never a finish.
  // ===========================================================================
  {
    id: 'mountain_climber',
    name: 'Mountain climber',
    description:
      'A tumbling C plus one medium step forward — or a lunge with the back knee bent and a C upper body. Two bent knees. Reach from the middle out. Pass-through only; never a finish.',
    bodyPosition:
      'SIDE VIEW. Take a C shape and step one medium step forward — not as big as a lunge. Or take a lunge, bend the back knee, and C-shape the upper half. Both knees BEND (two bent knees to generate speed and power into a kick and push). Upper body is the tumbling C: hips under, chest hollow, rounded back. Arms reach forward and out from the middle — not from the top down after a hurdle. Either leg forward. We never finish a skill here.',
    category: 'static',
    qualityThreshold: 60,
    cameraView: 'side',
    stanceAware: true,
    tips: [
      'C plus one medium step — not as big as a lunge.',
      'Both knees bent — that is the power for the kick and push.',
      'C-shape the upper body. Do not keep a straight-back open-shoulder lunge line.',
      'Reach forward and out from the middle, not from the top down.',
      'Pass-through only. We never finish a skill in this shape.',
    ],
    coachNotes:
      'A mountain climber is a lunge and a C shape combined: take a C and step one medium step forward (not as big as a lunge), or take a lunge, bend the back knee, and C-shape the upper half. Two bent knees generate speed and power into a kick and push. It also trains reaching forward and out rather than taking the hands from the top down after a hurdle — from the middle and out forward is the goal for long cartwheels and round-offs. Good pass-through for entering handstands, cartwheels, round-offs, standing aerials, front aerials, and front handsprings. We never finish a skill in this position. Into a cartwheel, look ahead of you rather than too far down. Into a handstand, look at where the hands will go. Cartwheels can also start from a starting lunge: lunges keep the back leg straight, the back straight, and the shoulders open.',
    criteria: [
      {
        id: 'medium_step',
        label: 'Medium step',
        kind: 'point_distance',
        pair: [LM.LEFT_ANKLE, LM.RIGHT_ANKLE],
        targetMin: 0.1,
        targetMax: 0.22,
        tolerance: 0.04,
        falloff: 0.2,
        weight: 14,
        feedbackLow: 'Take a medium step forward — C plus one step.',
        feedbackHigh: 'Medium step — not as big as a lunge.',
      },
      {
        id: 'front_knee',
        label: 'Front knee bent',
        kind: 'joint_angle',
        points: L_KNEE,
        targetMin: 70,
        targetMax: 120,
        tolerance: 15,
        weight: 16,
        feedbackLow: 'Bend the front knee — two bent knees for power.',
        feedbackHigh: 'Keep a clear bend in the front knee.',
      },
      {
        id: 'back_knee_bent',
        label: 'Back knee bent',
        kind: 'joint_angle',
        points: R_KNEE,
        targetMin: 90,
        targetMax: 145,
        tolerance: 12,
        falloff: 40,
        weight: 22,
        feedbackLow: 'Bend the back knee — two bent knees for the kick and push.',
        feedbackHigh: 'Keep a clear bend in the back knee — this is not a lunge.',
      },
      {
        id: 'upper_c',
        label: 'Upper body C',
        kind: 'joint_angle',
        points: [LM.LEFT_SHOULDER, LM.LEFT_HIP, LM.LEFT_KNEE],
        targetMin: 130,
        targetMax: 165,
        tolerance: 15,
        falloff: 45,
        weight: 22,
        feedbackLow: 'C-shape the upper half — hips under, chest hollow.',
        feedbackHigh: 'Keep the C — this is not a straight-back lunge.',
      },
      {
        id: 'arms_forward',
        label: 'Reach from the middle out',
        kind: 'segment_vs_horizontal',
        segment: [LM.LEFT_SHOULDER, LM.LEFT_WRIST],
        targetMin: 15,
        targetMax: 55,
        tolerance: 12,
        falloff: 40,
        weight: 16,
        needsView: 'side',
        feedbackLow: 'Reach forward and out from the middle — not hanging down.',
        feedbackHigh: 'From the middle out forward — not from the top down by the ears.',
      },
      {
        id: 'elbows',
        label: 'Elbows straight',
        kind: 'joint_angle',
        points: L_ELBOW,
        targetMin: 155,
        targetMax: 180,
        tolerance: 10,
        weight: 10,
        feedbackLow: 'Straighten elbows.',
      },
    ],
  },

  // ===========================================================================
  // SEATED PIKE — arms covering ears, looking through hands
  // ===========================================================================
  {
    id: 'seated_pike',
    name: 'Seated pike',
    description: 'Seated pike fold with arms covering ears, eyes looking through the hands.',
    category: 'static',
    qualityThreshold: 60,
    criteria: [
      {
        id: 'pike_fold',
        label: 'Pike fold (hips)',
        kind: 'joint_angle',
        points: L_HIP,
        targetMin: 20,
        targetMax: 70,
        tolerance: 15,
        falloff: 50,
        weight: 30,
        feedbackHigh: 'Fold deeper over the legs ({delta}°).',
        feedbackLow: 'Ease the fold slightly.',
      },
      {
        id: 'knees',
        label: 'Knees straight',
        kind: 'joint_angle',
        points: L_KNEE,
        targetMin: 160,
        targetMax: 180,
        tolerance: 8,
        weight: 25,
        feedbackLow: 'Straighten knees {delta}°.',
      },
      {
        id: 'arms_by_ears',
        label: 'Arms covering ears',
        kind: 'joint_angle',
        points: L_SHOULDER,
        targetMin: 140,
        targetMax: 180,
        tolerance: 12,
        weight: 25,
        feedbackLow: 'Reach arms longer by the ears ({delta}°).',
      },
      {
        id: 'elbows',
        label: 'Elbows straight',
        kind: 'joint_angle',
        points: L_ELBOW,
        targetMin: 155,
        targetMax: 180,
        tolerance: 10,
        weight: 12,
        feedbackLow: 'Straighten elbows.',
      },
      {
        id: 'feet_together',
        label: 'Feet together',
        kind: 'point_distance',
        pair: [LM.LEFT_ANKLE, LM.RIGHT_ANKLE],
        target: 0,
        tolerance: 0.08,
        falloff: 0.2,
        weight: 8,
        feedbackHigh: 'Keep feet together.',
      },
    ],
  },

  // ===========================================================================
  // HOLLOW (ARMS UP) — progression after a proper 1-minute arms-down hold
  // ===========================================================================
  {
    id: 'hollow_arms_up',
    name: 'Hollow (arms up)',
    description:
      'Hollow body hold with arms glued to the ears. Same lower-back compression as arms-down, longer lever. Only after a proper 1-minute arms-down hold.',
    bodyPosition:
      'SIDE VIEW, on the back. Same hollow as arms-down: lower back pressed into the floor, ribs in, legs together and off the floor, toes pointed. Arms glued by the ears, elbows straight. Do not use this yet unless you can hold hollow arms-down properly for a minute.',
    category: 'hold',
    qualityThreshold: 65,
    cameraView: 'side',
    tips: [
      'Only after a proper 1-minute hollow with arms down.',
      'Same lower-back rule — no gap.',
      'Arms by the ears, not a sit-up.',
    ],
    coachNotes:
      'Only do this if you can already hold hollow arms-down for a minute properly. Same body as the round-off / back handspring / whip / layout / full shape, with a longer lever. Training this poorly still leads to piking out of those skills.',
    criteria: [
      {
        id: 'shoulder_open',
        label: 'Arms by ears',
        kind: 'joint_angle',
        points: L_SHOULDER,
        targetMin: 140,
        targetMax: 180,
        tolerance: 12,
        weight: 22,
        feedbackLow: 'Cover ears — open shoulders {delta}°.',
      },
      {
        id: 'hips',
        label: 'Hollow hip angle',
        kind: 'joint_angle',
        points: L_HIP,
        targetMin: 120,
        targetMax: 155,
        tolerance: 12,
        falloff: 40,
        weight: 28,
        feedbackLow: 'Hollow more (posterior tilt).',
        feedbackHigh: 'Reduce pike — lengthen hollow.',
      },
      {
        id: 'knees',
        label: 'Knees straight',
        kind: 'joint_angle',
        points: L_KNEE,
        targetMin: 160,
        targetMax: 180,
        tolerance: 8,
        weight: 20,
        feedbackLow: 'Straighten knees {delta}°.',
      },
      {
        id: 'elbows',
        label: 'Elbows straight',
        kind: 'joint_angle',
        points: L_ELBOW,
        targetMin: 155,
        targetMax: 180,
        tolerance: 10,
        weight: 15,
        feedbackLow: 'Straighten elbows.',
      },
      {
        id: 'feet_together',
        label: 'Feet together',
        kind: 'point_distance',
        pair: [LM.LEFT_ANKLE, LM.RIGHT_ANKLE],
        target: 0,
        tolerance: 0.07,
        falloff: 0.2,
        weight: 15,
        feedbackHigh: 'Squeeze heels together.',
      },
      {
        id: 'legs_lifted',
        label: 'Legs just off floor',
        kind: 'segment_vs_horizontal',
        segment: [LM.LEFT_HIP, LM.LEFT_ANKLE],
        targetMin: 5,
        targetMax: 40,
        tolerance: 8,
        falloff: 40,
        weight: 10,
        feedbackLow: 'Lift the legs slightly off the floor.',
        feedbackHigh: 'Lower the legs — keep the lower back pressed down.',
      },
      {
        id: 'upper_lift',
        label: 'Shoulders off floor',
        kind: 'segment_vs_horizontal',
        segment: [LM.LEFT_HIP, LM.LEFT_SHOULDER],
        targetMin: 5,
        targetMax: 45,
        tolerance: 10,
        falloff: 45,
        weight: 8,
        feedbackLow: 'Curl the shoulders slightly off the floor.',
        feedbackHigh: 'Lower the chest — small curl, not a sit-up.',
      },
      {
        id: 'toes',
        label: 'Toes pointed',
        kind: 'segment_vs_horizontal',
        segment: [LM.LEFT_HEEL, LM.LEFT_FOOT_INDEX],
        target: 0,
        tolerance: 25,
        falloff: 50,
        weight: 6,
        needsView: 'side',
        feedbackHigh: 'Point the toes ({delta}°).',
      },
    ],
  },

  // ===========================================================================
  // HOLLOW (ARMS DOWN) — beginner hollow, homework auto-drill stage 1
  // Side view, on the back. Start from a pike and inch back until the lower
  // back is flat. Level up to arms-by-ears hollow after 60s quality hold.
  // ===========================================================================
  {
    id: 'hollow_arms_down',
    name: 'Hollow (arms down)',
    description:
      'Hollow body hold with arms down: lower back compressed to the floor, arms by the sides, feet off the ground. Tumbling staple — round-off, back handspring, whip, layouts, fulls.',
    bodyPosition:
      'SIDE VIEW, on the back. Start in a pike and inch back until the lower back is flat — do not sit up from a lying position. Compress the lower back into the floor and let the feet lift. Arms stay down by the sides (reaching toward the knees). Shoulders and head just off the floor. Legs together, knees straight, toes pointed. If the lower back will not go down, bend the knees.',
    category: 'hold',
    qualityThreshold: 65,
    cameraView: 'side',
    tips: [
      'SIDE VIEW while lying on your back.',
      'Start in a pike and inch back until the lower back is flat.',
      'Press the lower back down first — then let the feet lift.',
      'Arms by the sides, not overhead.',
      'If the lower back will not go down, bend the knees.',
      'Hold this properly for a minute, then try arms glued to the ears.',
    ],
    coachNotes:
      'Another tumbling staple. It helps to start in a pike and inch back until the lower back is flat rather than trying to lift up into this from a supine position. Get the lower back compressed to the floor and let the feet lift off the ground. If the athlete cannot get the lower back to the ground, try bending the knees. If they can easily hold this properly for a minute, try it with arms glued to the ears. This body position happens exiting a round-off, back handspring, and whip, and is often the main shape held on layouts and fulls. Athletes who train this improperly have a higher likelihood of piking out of round-offs, handsprings, and layouts, and may struggle with skills that need lots of abdominal stability.',
    criteria: [
      {
        // Arms DOWN by the sides → SMALL hip–shoulder–elbow angle
        // (the arms-up hollow wants this LARGE instead).
        id: 'arms_down',
        label: 'Arms by sides',
        kind: 'joint_angle',
        points: L_SHOULDER,
        targetMin: 0,
        targetMax: 45,
        tolerance: 12,
        falloff: 45,
        weight: 20,
        feedbackHigh: 'Keep arms down by your sides — not by the ears yet ({delta}° too high).',
      },
      {
        // Lower-back compression proxy 1: hollow hip band
        // (same band as the arms-up hollow).
        id: 'hips',
        label: 'Hollow hip angle',
        kind: 'joint_angle',
        points: L_HIP,
        targetMin: 120,
        targetMax: 155,
        tolerance: 12,
        falloff: 40,
        weight: 26,
        feedbackLow: 'Hollow more — press the lower back into the floor.',
        feedbackHigh: 'Reduce pike — lengthen the hollow.',
      },
      {
        id: 'knees',
        label: 'Knees straight',
        kind: 'joint_angle',
        points: L_KNEE,
        targetMin: 160,
        targetMax: 180,
        tolerance: 8,
        weight: 18,
        feedbackLow: 'Straighten knees {delta}°.',
      },
      {
        // Lower-back compression proxy 2: legs slightly off the floor.
        id: 'legs_lifted',
        label: 'Legs just off floor',
        kind: 'segment_vs_horizontal',
        segment: [LM.LEFT_HIP, LM.LEFT_ANKLE],
        targetMin: 5,
        targetMax: 40,
        tolerance: 8,
        falloff: 40,
        weight: 12,
        feedbackLow: 'Lift the legs slightly off the floor.',
        feedbackHigh: 'Lower the legs — keep the lower back pressed down.',
      },
      {
        // Lower-back compression proxy 3: shoulders slightly off the floor.
        id: 'upper_lift',
        label: 'Shoulders off floor',
        kind: 'segment_vs_horizontal',
        segment: [LM.LEFT_HIP, LM.LEFT_SHOULDER],
        targetMin: 5,
        targetMax: 45,
        tolerance: 10,
        falloff: 45,
        weight: 10,
        feedbackLow: 'Curl the shoulders slightly off the floor.',
        feedbackHigh: 'Lower the chest — small curl, not a sit-up.',
      },
      {
        id: 'feet_together',
        label: 'Feet together',
        kind: 'point_distance',
        pair: [LM.LEFT_ANKLE, LM.RIGHT_ANKLE],
        target: 0,
        tolerance: 0.07,
        falloff: 0.2,
        weight: 14,
        feedbackHigh: 'Squeeze heels together.',
      },
      {
        id: 'toes',
        label: 'Toes pointed',
        kind: 'segment_vs_horizontal',
        segment: [LM.LEFT_HEEL, LM.LEFT_FOOT_INDEX],
        target: 0,
        tolerance: 25,
        falloff: 50,
        weight: 8,
        needsView: 'side',
        feedbackHigh: 'Point the toes ({delta}°).',
      },
    ],
  },

  // ===========================================================================
  // ARCH
  // ===========================================================================
  {
    id: 'arch',
    name: 'Arch',
    description: 'Prone arch: chest and thighs lifted, arms by ears or reaching long.',
    category: 'hold',
    qualityThreshold: 60,
    criteria: [
      {
        id: 'hip_extension',
        label: 'Hip extension',
        kind: 'joint_angle',
        points: L_HIP,
        targetMin: 160,
        targetMax: 200,
        tolerance: 15,
        falloff: 45,
        weight: 30,
        feedbackLow: 'Lift thighs / open hips into the arch.',
      },
      {
        id: 'shoulders',
        label: 'Shoulders open',
        kind: 'joint_angle',
        points: L_SHOULDER,
        targetMin: 130,
        targetMax: 180,
        tolerance: 15,
        weight: 25,
        feedbackLow: 'Reach arms longer by the ears.',
      },
      {
        id: 'knees',
        label: 'Knees straight',
        kind: 'joint_angle',
        points: L_KNEE,
        targetMin: 155,
        targetMax: 180,
        tolerance: 10,
        weight: 25,
        feedbackLow: 'Straighten knees.',
      },
      {
        id: 'feet_together',
        label: 'Feet together',
        kind: 'point_distance',
        pair: [LM.LEFT_ANKLE, LM.RIGHT_ANKLE],
        target: 0,
        tolerance: 0.08,
        falloff: 0.2,
        weight: 20,
        feedbackHigh: 'Keep legs glued together.',
      },
    ],
  },

  // ===========================================================================
  // SUPERMAN — homework auto-drill
  // Prone hold: STRAIGHT arms behind the ears, chin OFF the chest (head
  // neutral / slightly lifted), straight knees lifted off the ground,
  // pointed toes, feet and ankles squeezed together. Film from the side.
  // ===========================================================================
  {
    id: 'superman',
    name: 'Superman',
    description:
      'Prone Superman hold: straight arms behind the ears, chin off the chest (head neutral), straight knees lifted off the floor, feet and ankles together, toes pointed.',
    category: 'hold',
    qualityThreshold: 60,
    tips: [
      'Film from the side while lying on your stomach.',
      'Arms straight and squeezed behind the ears.',
      'Chin OFF the chest — head neutral or slightly lifted.',
      'Lift straight knees off the ground.',
      'Squeeze feet and ankles together and point the toes hard.',
    ],
    criteria: [
      {
        // Arms behind ears → LARGE hip–shoulder–elbow angle.
        id: 'arms_behind_ears',
        label: 'Arms behind ears',
        kind: 'joint_angle',
        points: L_SHOULDER,
        targetMin: 150,
        targetMax: 180,
        tolerance: 12,
        weight: 20,
        feedbackLow: 'Squeeze straight arms behind the ears ({delta}° more).',
      },
      {
        id: 'elbows',
        label: 'Elbows straight',
        kind: 'joint_angle',
        points: L_ELBOW,
        targetMin: 155,
        targetMax: 180,
        tolerance: 10,
        weight: 12,
        feedbackLow: 'Straighten elbows — long arms.',
      },
      {
        // Head neutral proxy: shoulder→nose segment lifted slightly
        // above the (horizontal) prone torso line.
        id: 'chin_off_chest',
        label: 'Chin off chest',
        kind: 'segment_vs_horizontal',
        segment: [LM.LEFT_SHOULDER, LM.NOSE],
        targetMin: 5,
        targetMax: 50,
        tolerance: 10,
        falloff: 40,
        weight: 14,
        feedbackLow: 'Lift the chin off the chest — head neutral.',
        feedbackHigh: 'Relax the neck — head neutral, not cranked up.',
      },
      {
        // Straight knees lifted off the ground → open (even hyper-extended)
        // shoulder–hip–knee angle.
        id: 'legs_lifted',
        label: 'Knees off floor',
        kind: 'joint_angle',
        points: L_HIP,
        targetMin: 150,
        targetMax: 200,
        tolerance: 15,
        weight: 20,
        feedbackLow: 'Lift straight knees off the floor.',
      },
      {
        id: 'knees',
        label: 'Knees straight',
        kind: 'joint_angle',
        points: L_KNEE,
        targetMin: 160,
        targetMax: 180,
        tolerance: 8,
        weight: 16,
        feedbackLow: 'Straighten knees {delta}° — pointed toes.',
      },
      {
        id: 'feet_ankles_together',
        label: 'Feet & ankles together',
        kind: 'point_distance',
        pair: [LM.LEFT_ANKLE, LM.RIGHT_ANKLE],
        target: 0,
        tolerance: 0.06,
        falloff: 0.2,
        weight: 18,
        feedbackHigh: 'Squeeze feet and ankles together.',
      },
    ],
  },

  // ===========================================================================
  // BRIDGE
  // ===========================================================================
  {
    id: 'bridge',
    name: 'Bridge',
    description: 'Back bridge / backbend: hips high, shoulders open, legs engaged.',
    category: 'hold',
    qualityThreshold: 60,
    criteria: [
      {
        id: 'shoulders',
        label: 'Shoulders open',
        kind: 'joint_angle',
        points: L_SHOULDER,
        targetMin: 140,
        targetMax: 180,
        tolerance: 15,
        weight: 30,
        feedbackLow: 'Push shoulders open over the hands.',
      },
      {
        id: 'hips_high',
        label: 'Hips open',
        kind: 'joint_angle',
        points: L_HIP,
        targetMin: 130,
        targetMax: 180,
        tolerance: 15,
        weight: 30,
        feedbackLow: 'Push hips higher.',
      },
      {
        id: 'elbows',
        label: 'Elbows straight',
        kind: 'joint_angle',
        points: L_ELBOW,
        targetMin: 155,
        targetMax: 180,
        tolerance: 10,
        weight: 20,
        feedbackLow: 'Straighten arms.',
      },
      {
        id: 'knee_symmetry',
        label: 'Leg symmetry',
        kind: 'symmetry',
        leftPoints: L_KNEE,
        rightPoints: R_KNEE,
        target: 0,
        tolerance: 15,
        falloff: 40,
        weight: 20,
        feedbackHigh: 'Even the legs — difference {delta}°.',
      },
    ],
  },

  // ===========================================================================
  // CANDLESTICK — shoulder stand; open hips + ribs in (handstand forward roll / BER)
  // ===========================================================================
  {
    id: 'candlestick',
    name: 'Candlestick',
    description:
      'Shoulder-stand candlestick: open hips, ribs in, straight vertical line from shoulders to pointed toes. Staple for tumbling and straight-arm handstand forward rolls.',
    bodyPosition:
      'SIDE or 3/4. Weight on the shoulders and upper back. Hips OPEN and stacked over the shoulders. Ribs in — no banana. Knees straight, feet together, toes pointed to the ceiling. One straight vertical line. Arms can rest on the floor by the ears / reaching past the head.',
    category: 'hold',
    qualityThreshold: 65,
    cameraView: 'side',
    tips: [
      'SIDE or 3/4 so the vertical line is obvious.',
      'Open hips, ribs in — same stacked body as a good handstand, just on the shoulders.',
      'Straight knees, pointed toes.',
    ],
    coachNotes:
      'A staple in gymnastics and tumbling. This still is the middle of a handstand forward roll. Useful for learning open hips with ribs in, entering the back extension roll, and exiting the handstand into a forward roll. Good handstand forward rolls with straight arms require this shape. Also useful for drills that apply to handsprings, tucks, layouts, and fulls.',
    criteria: [
      {
        id: 'legs_vertical',
        label: 'Legs vertical',
        kind: 'segment_vs_vertical',
        segment: [LM.LEFT_HIP, LM.LEFT_ANKLE],
        target: 0,
        tolerance: 15,
        falloff: 40,
        weight: 30,
        needsView: 'side',
        feedbackHigh: 'Stack legs vertical — {delta}° off.',
      },
      {
        id: 'hips',
        label: 'Open hips / ribs in',
        kind: 'joint_angle',
        points: L_HIP,
        targetMin: 155,
        targetMax: 180,
        tolerance: 10,
        weight: 24,
        feedbackLow: 'Open the hips — ribs in, no pike.',
        feedbackHigh: 'Ribs in — don’t arch.',
      },
      {
        id: 'knees',
        label: 'Knees straight',
        kind: 'joint_angle',
        points: L_KNEE,
        targetMin: 160,
        targetMax: 180,
        tolerance: 8,
        weight: 20,
        feedbackLow: 'Straighten knees.',
      },
      {
        id: 'feet_together',
        label: 'Feet together',
        kind: 'point_distance',
        pair: [LM.LEFT_ANKLE, LM.RIGHT_ANKLE],
        target: 0,
        tolerance: 0.07,
        falloff: 0.2,
        weight: 12,
        feedbackHigh: 'Squeeze feet together.',
      },
      {
        id: 'toes',
        label: 'Toes pointed',
        kind: 'segment_vs_vertical',
        segment: [LM.LEFT_HEEL, LM.LEFT_FOOT_INDEX],
        target: 0,
        tolerance: 22,
        falloff: 50,
        weight: 14,
        needsView: 'side',
        feedbackHigh: 'Point the toes ({delta}°).',
      },
    ],
  },

  // ===========================================================================
  // PASSÉ — FTOS lines + one knee up, open shoulders, arms by ears (task 3)
  // ===========================================================================
  {
    id: 'passe',
    name: 'Passé',
    description:
      'Keep feet-together open-shoulders lines, then pull one knee up into passé. Open shoulders, arms by ears.',
    bodyPosition:
      'Keep the FTOS upper body: arms to the ceiling, open shoulders, elbows straight. Stance leg stays straight. The other foot pulls up to the knee (passé). Hips square, torso tall. Either knee may lift — the app auto-detects the side.',
    category: 'static',
    qualityThreshold: 65,
    cameraView: 'any',
    stanceAware: true,
    tips: [
      'Match the reference: stance leg straight, passé foot at the knee, arms reaching to the ceiling.',
      'Keep FTOS lines — open shoulders, arms by ears, elbows straight.',
      'Hips square and torso tall; don’t lean into the passé hip.',
    ],
    coachNotes:
      'Pull this from feet-together open shoulders. Keep the same upper-body line: ribs in, open shoulders, hands to the ceiling.',
    criteria: [
      {
        id: 'stance_knee',
        label: 'Stance knee straight',
        kind: 'joint_angle',
        points: L_KNEE,
        targetMin: 165,
        targetMax: 180,
        tolerance: 5,
        weight: 16,
        feedbackLow: 'Straighten the standing leg.',
      },
      {
        id: 'passe_height',
        label: 'Passé knee up',
        kind: 'point_distance',
        pair: [LM.RIGHT_ANKLE, LM.LEFT_KNEE],
        target: 0,
        tolerance: 0.12,
        falloff: 0.25,
        weight: 20,
        feedbackHigh: 'Pull passé foot up to the knee.',
      },
      {
        id: 'hips',
        label: 'Hips open / tall',
        kind: 'joint_angle',
        points: L_HIP,
        targetMin: 155,
        targetMax: 180,
        tolerance: 10,
        weight: 12,
        feedbackLow: 'Stay tall through the hips.',
      },
      {
        id: 'shoulders',
        label: 'Open shoulders',
        kind: 'joint_angle',
        points: L_SHOULDER,
        targetMin: 150,
        targetMax: 180,
        tolerance: 10,
        weight: 18,
        feedbackLow: 'Open shoulders — arms by ears.',
      },
      {
        id: 'elbows',
        label: 'Elbows straight',
        kind: 'joint_angle',
        points: L_ELBOW,
        targetMin: 160,
        targetMax: 180,
        tolerance: 8,
        weight: 12,
        feedbackLow: 'Straighten elbows.',
      },
      {
        id: 'hands_up',
        label: 'Arms by ears',
        kind: 'segment_vs_vertical',
        segment: [LM.LEFT_SHOULDER, LM.LEFT_WRIST],
        target: 0,
        tolerance: 18,
        falloff: 40,
        weight: 12,
        feedbackHigh: 'Reach arms up by the ears ({delta}°).',
      },
      {
        id: 'torso',
        label: 'Torso upright',
        kind: 'segment_vs_vertical',
        segment: [LM.LEFT_HIP, LM.LEFT_SHOULDER],
        target: 0,
        tolerance: 12,
        falloff: 40,
        weight: 8,
        feedbackHigh: 'Stand taller — torso {delta}° off vertical.',
      },
      {
        id: 'hips_square',
        label: 'Hips square',
        kind: 'symmetry',
        leftPoints: L_HIP,
        rightPoints: R_HIP,
        target: 0,
        tolerance: 18,
        falloff: 45,
        weight: 8,
        feedbackHigh: 'Square the hips — left/right differ by {delta}°.',
      },
    ],
  },

  // ===========================================================================
  // TUCKED HANDSTAND
  // ===========================================================================
  {
    id: 'tucked_handstand',
    name: 'Tucked handstand',
    description: 'Handstand with hips piked and knees tucked, shoulders open on top of hands.',
    category: 'hold',
    qualityThreshold: 60,
    criteria: [
      {
        id: 'elbows',
        label: 'Elbows straight',
        kind: 'joint_angle',
        points: L_ELBOW,
        targetMin: 160,
        targetMax: 180,
        tolerance: 8,
        weight: 25,
        feedbackLow: 'Straighten elbows.',
      },
      {
        id: 'shoulders',
        label: 'Shoulders open',
        kind: 'joint_angle',
        points: L_SHOULDER,
        targetMin: 145,
        targetMax: 180,
        tolerance: 12,
        weight: 25,
        feedbackLow: 'Open shoulders over the hands.',
      },
      {
        id: 'tuck_knees',
        label: 'Knees tucked',
        kind: 'joint_angle',
        points: L_KNEE,
        targetMin: 30,
        targetMax: 90,
        tolerance: 15,
        falloff: 50,
        weight: 25,
        feedbackHigh: 'Tuck knees tighter.',
        feedbackLow: 'Keep a clear tuck shape.',
      },
      {
        id: 'balance_line',
        label: 'Stack over hands',
        kind: 'segment_vs_vertical',
        segment: [LM.LEFT_WRIST, LM.LEFT_HIP],
        target: 0,
        tolerance: 18,
        falloff: 45,
        weight: 25,
        feedbackHigh: 'Stack hips over hands ({delta}°).',
      },
    ],
  },

  // ===========================================================================
  // PIKED HANDSTAND
  // ===========================================================================
  {
    id: 'piked_handstand',
    name: 'Piked handstand',
    description: 'Handstand with a clear pike at the hips, legs straight.',
    category: 'hold',
    qualityThreshold: 60,
    criteria: [
      {
        id: 'elbows',
        label: 'Elbows straight',
        kind: 'joint_angle',
        points: L_ELBOW,
        targetMin: 160,
        targetMax: 180,
        tolerance: 8,
        weight: 22,
        feedbackLow: 'Straighten elbows.',
      },
      {
        id: 'shoulders',
        label: 'Shoulders open',
        kind: 'joint_angle',
        points: L_SHOULDER,
        targetMin: 145,
        targetMax: 180,
        tolerance: 12,
        weight: 22,
        feedbackLow: 'Open shoulders.',
      },
      {
        id: 'pike',
        label: 'Pike angle',
        kind: 'joint_angle',
        points: L_HIP,
        targetMin: 60,
        targetMax: 120,
        tolerance: 15,
        falloff: 45,
        weight: 28,
        feedbackLow: 'Pike more at the hips.',
        feedbackHigh: 'Keep a clearer pike (less open).',
      },
      {
        id: 'knees',
        label: 'Knees straight',
        kind: 'joint_angle',
        points: L_KNEE,
        targetMin: 160,
        targetMax: 180,
        tolerance: 8,
        weight: 18,
        feedbackLow: 'Straighten knees in the pike.',
      },
      {
        id: 'feet_together',
        label: 'Feet together',
        kind: 'point_distance',
        pair: [LM.LEFT_ANKLE, LM.RIGHT_ANKLE],
        target: 0,
        tolerance: 0.08,
        falloff: 0.2,
        weight: 10,
        feedbackHigh: 'Keep feet together.',
      },
    ],
  },

  // ===========================================================================
  // L HANDSTAND
  // ===========================================================================
  {
    id: 'l_handstand',
    name: 'L handstand',
    description: 'L-shape handstand: one line vertical through arms/torso, legs near horizontal.',
    category: 'hold',
    qualityThreshold: 60,
    criteria: [
      {
        id: 'arms_vertical',
        label: 'Arms vertical',
        kind: 'segment_vs_vertical',
        segment: [LM.LEFT_WRIST, LM.LEFT_SHOULDER],
        target: 0,
        tolerance: 15,
        falloff: 40,
        weight: 28,
        feedbackHigh: 'Stack arms vertical ({delta}°).',
      },
      {
        id: 'legs_horizontal',
        label: 'Legs horizontal',
        kind: 'segment_vs_horizontal',
        segment: [LM.LEFT_HIP, LM.LEFT_ANKLE],
        target: 0,
        tolerance: 20,
        falloff: 45,
        weight: 28,
        feedbackHigh: 'Bring legs toward horizontal L ({delta}°).',
      },
      {
        id: 'elbows',
        label: 'Elbows straight',
        kind: 'joint_angle',
        points: L_ELBOW,
        targetMin: 160,
        targetMax: 180,
        tolerance: 8,
        weight: 22,
        feedbackLow: 'Straighten elbows.',
      },
      {
        id: 'knees',
        label: 'Knees straight',
        kind: 'joint_angle',
        points: L_KNEE,
        targetMin: 160,
        targetMax: 180,
        tolerance: 8,
        weight: 22,
        feedbackLow: 'Straighten knees.',
      },
    ],
  },

  // ===========================================================================
  // WALL HANDSTAND
  // ===========================================================================
  {
    id: 'wall_handstand',
    name: 'Wall handstand',
    description: 'Handstand at the wall — same body standards as freestanding, slightly more forgiving line.',
    category: 'hold',
    qualityThreshold: 65,
    tips: [
      'Use the same cues as freestanding handstand.',
      'Prefer stomach-to-wall for open shoulders.',
      'Ribs in, butt in, straight elbows, cover the ears, point the toes, push tall.',
    ],
    criteria: [
      {
        id: '_left_elbow',
        label: 'Left elbow',
        kind: 'joint_angle',
        points: L_ELBOW,
        targetMin: 160,
        targetMax: 180,
        tolerance: 8,
        weight: 1,
        feedbackLow: 'Straighten left elbow.',
      },
      {
        id: '_right_elbow',
        label: 'Right elbow',
        kind: 'joint_angle',
        points: R_ELBOW,
        targetMin: 160,
        targetMax: 180,
        tolerance: 8,
        weight: 1,
        feedbackLow: 'Straighten right elbow.',
      },
      {
        id: 'elbows',
        label: 'Elbows',
        kind: 'composite_min',
        of: ['_left_elbow', '_right_elbow'],
        tolerance: 0,
        weight: 25,
      },
      {
        id: 'shoulders',
        label: 'Shoulders',
        kind: 'joint_angle',
        points: L_SHOULDER,
        targetMin: 145,
        targetMax: 180,
        tolerance: 12,
        weight: 25,
        feedbackLow: 'Open shoulders {delta}° more.',
      },
      {
        id: 'hips',
        label: 'Hips',
        kind: 'joint_angle',
        points: L_HIP,
        targetMin: 155,
        targetMax: 180,
        tolerance: 10,
        weight: 20,
        feedbackLow: 'Open hips / reduce pike.',
      },
      {
        id: 'knees',
        label: 'Knees',
        kind: 'joint_angle',
        points: L_KNEE,
        targetMin: 160,
        targetMax: 180,
        tolerance: 8,
        weight: 15,
        feedbackLow: 'Straighten knees.',
      },
      {
        id: 'body_line',
        label: 'Body line',
        kind: 'segment_vs_vertical',
        segment: [LM.LEFT_SHOULDER, LM.LEFT_ANKLE],
        target: 0,
        tolerance: 18,
        falloff: 45,
        weight: 15,
        feedbackHigh: 'Tighten body line — {delta}° off vertical.',
      },
    ],
  },

  // ===========================================================================
  // C SHAPE — tumbling C (back handspring / roundoff / mountain climber)
  // SIDE view: squat, hollow chest, hips under, arms reaching forward.
  // ===========================================================================
  {
    id: 'c_shape',
    name: 'C shape',
    description:
      'Tumbling C: squat with a hollow rounded torso, hips under, arms reaching forward. Used to connect into a back handspring.',
    bodyPosition:
      'SIDE VIEW. Feet together (or close), flat on the floor. Knees bent in a partial squat. Hips tucked under. Chest hollow, shoulders rounded forward so the back makes a clear C from shoulders to tailbone. Arms reach straight forward and slightly up, elbows locked. Wrists can flex so palms face away. Head follows the curve — look toward the hands. This is not a standing side-bend.',
    category: 'static',
    qualityThreshold: 60,
    cameraView: 'side',
    tips: [
      'SIDE VIEW — stand in profile so the C is obvious.',
      'Hips under, chest hollow — round the back, do not arch.',
      'Arms reach forward (not by the ears). Elbows straight.',
      'This C plus one medium step forward is a mountain climber.',
    ],
    coachNotes:
      'C shape is used for connecting into a back handspring. Commonly used when teaching round-off back handspring connection. A mountain climber is this C plus one medium step forward, with the back knee bent. We may pull a passé from the C shape before going into a cartwheel or a round-off. I commonly teach back extension rolls starting from this shape.',
    criteria: [
      {
        id: 'knees_bent',
        label: 'Knees bent (squat)',
        kind: 'joint_angle',
        points: L_KNEE,
        targetMin: 85,
        targetMax: 130,
        tolerance: 12,
        falloff: 40,
        weight: 24,
        feedbackLow: 'Bend the knees — this C sits in a squat, not standing tall.',
        feedbackHigh: 'Come up a little — keep a squat, not a sit.',
      },
      {
        id: 'hollow_c',
        label: 'Hollow C (hips under)',
        kind: 'joint_angle',
        points: [LM.LEFT_SHOULDER, LM.LEFT_HIP, LM.LEFT_KNEE],
        targetMin: 70,
        targetMax: 130,
        tolerance: 12,
        falloff: 40,
        weight: 28,
        feedbackLow: 'Tuck the hips under and hollow the chest — make a C.',
        feedbackHigh: 'Keep the C — hips under, chest hollow.',
      },
      {
        id: 'arms_forward',
        label: 'Arms reaching forward',
        kind: 'segment_vs_horizontal',
        segment: [LM.LEFT_SHOULDER, LM.LEFT_WRIST],
        targetMin: 10,
        targetMax: 50,
        tolerance: 12,
        falloff: 40,
        weight: 24,
        needsView: 'side',
        feedbackLow: 'Lift the arms slightly — reach forward, not down.',
        feedbackHigh: 'Reach forward, not up by the ears.',
      },
      {
        id: 'elbows',
        label: 'Elbows straight',
        kind: 'joint_angle',
        points: L_ELBOW,
        targetMin: 150,
        targetMax: 180,
        tolerance: 12,
        weight: 14,
        feedbackLow: 'Straighten elbows.',
      },
      {
        id: 'feet_together',
        label: 'Feet close',
        kind: 'point_distance',
        pair: [LM.LEFT_ANKLE, LM.RIGHT_ANKLE],
        target: 0.06,
        tolerance: 0.06,
        falloff: 0.12,
        weight: 10,
        feedbackHigh: 'Keep the feet closer together.',
      },
    ],
  },

  // ===========================================================================
  // ZOMBIE — standing hollow, arms in front, shoulders shrugged to cover ears
  // Cartwheel step-in landing (RO prep). All RO / BHS land here until skills
  // above a round-off handspring series (then arms go up to block).
  // ===========================================================================
  {
    id: 'zombie',
    name: 'Zombie',
    description:
      'Standing hollow with half-closed shoulders. Straight knees. Butt in. Armpits in front of the toes. Landing for cartwheel step-ins, round-offs, and handsprings.',
    bodyPosition:
      'SIDE VIEW, standing. Hollow body with half-closed shoulder. Straight knees. Butt in. Armpits in front of the toes — that keeps the hollow if the hips want to push into an arch. Feet together. Arms reach forward; shrug so the arms cover the ears. Eyes forward/down toward where you came from. Same idea as candlestick and front support, standing upright. Not arms overhead — arms up only when blocking into a skill above a round-off handspring series.',
    category: 'hold',
    qualityThreshold: 60,
    cameraView: 'side',
    tips: [
      'Hollow body with half-closed shoulder.',
      'Straight knees.',
      'Butt in.',
      'Armpits in front of toes — that keeps the hollow if they push the hips into an arch.',
      'Eyes forward/down toward where you came from.',
      'SIDE VIEW, standing.',
    ],
    coachNotes:
      'Verbal cues: hollow body with half-closed shoulder. Straight knees. Butt in. Armpits in front of toes — use that if they are pushing the hips into an arch. Standing hollow with arms in front, shoulders shrugged so the arms cover the ears. Eyes look forward/down toward where they just came from — out of a cartwheel, round-off, handspring, or whip. Same idea as candlestick and front support, just standing upright. Helps get the chest up out of a round-off to a stand. Arms in front are where they can whip back to generate speed into a handspring or whip, and they speed rotation so the feet get in front — then we can keep momentum backwards with handspring connections. All round-offs and handsprings land here until the athlete is working skills above a round-off handspring series. Arms go up only when blocking into a higher skill. We train this shape on cartwheel step-ins before working round-offs. Usual cartwheels still finish in a landing lunge unless this landing is named.',
    criteria: [
      {
        // Hip–shoulder–elbow ~90° = half-closed (arms in front), not open ~170°.
        id: 'half_closed_shoulder',
        label: 'Half-closed shoulder',
        kind: 'joint_angle',
        points: L_SHOULDER,
        targetMin: 55,
        targetMax: 115,
        tolerance: 15,
        falloff: 40,
        weight: 20,
        feedbackLow: 'Hollow body with half-closed shoulder.',
        feedbackHigh: 'Hollow body with half-closed shoulder — not arms up.',
      },
      {
        id: 'knees',
        label: 'Straight knees',
        kind: 'joint_angle',
        points: L_KNEE,
        targetMin: 160,
        targetMax: 180,
        tolerance: 8,
        weight: 16,
        feedbackLow: 'Straight knees.',
      },
      {
        id: 'butt_in',
        label: 'Butt in',
        kind: 'joint_angle',
        points: L_HIP,
        targetMin: 148,
        targetMax: 172,
        tolerance: 8,
        falloff: 30,
        weight: 16,
        feedbackLow: 'Hollow body — don’t pike.',
        feedbackHigh: 'Butt in.',
      },
      {
        // Shoulder (armpit) should sit at or in front of the toes. If they
        // push the hips into an arch, the armpits drop behind the toes.
        id: 'armpits_front',
        label: 'Armpits in front of toes',
        kind: 'forward_of',
        pair: [LM.LEFT_SHOULDER, LM.LEFT_FOOT_INDEX],
        targetMin: -0.02,
        targetMax: 0.18,
        tolerance: 0.03,
        falloff: 0.12,
        weight: 18,
        needsView: 'side',
        feedbackLow: 'Armpits in front of toes — hollow, don’t push the hips into an arch.',
        feedbackHigh: 'Stay standing hollow — don’t dive the chest.',
      },
      {
        id: 'arms_forward',
        label: 'Arms in front',
        kind: 'segment_vs_horizontal',
        segment: [LM.LEFT_SHOULDER, LM.LEFT_WRIST],
        targetMin: 0,
        targetMax: 25,
        tolerance: 12,
        falloff: 40,
        weight: 10,
        needsView: 'side',
        feedbackLow: 'Reach the arms forward — not down by the hips.',
        feedbackHigh: 'Keep arms in front — not up overhead.',
      },
      {
        id: 'ears_covered',
        label: 'Shoulders shrug / ears covered',
        kind: 'point_distance',
        pair: [LM.LEFT_ELBOW, LM.LEFT_EAR],
        target: 0,
        tolerance: 0.12,
        falloff: 0.22,
        weight: 8,
        feedbackHigh: 'Shrug the shoulders up so the arms cover the ears.',
      },
      {
        id: 'eyes_down',
        label: 'Eyes forward / down',
        kind: 'segment_vs_vertical',
        segment: [LM.LEFT_SHOULDER, LM.NOSE],
        targetMin: 22,
        targetMax: 70,
        tolerance: 12,
        falloff: 40,
        weight: 6,
        needsView: 'side',
        feedbackLow: 'Look forward/down toward where you came from — not chin up.',
        feedbackHigh: 'Eyes forward/down, not a full sit-up tuck.',
      },
      {
        id: 'elbows',
        label: 'Elbows straight',
        kind: 'joint_angle',
        points: L_ELBOW,
        targetMin: 155,
        targetMax: 180,
        tolerance: 10,
        weight: 6,
        feedbackLow: 'Straighten elbows.',
      },
      {
        id: 'feet_together',
        label: 'Feet together',
        kind: 'point_distance',
        pair: [LM.LEFT_ANKLE, LM.RIGHT_ANKLE],
        target: 0,
        tolerance: 0.07,
        falloff: 0.2,
        weight: 4,
        feedbackHigh: 'Squeeze the feet together.',
      },
    ],
  },

  // ===========================================================================
  // SIDE PLANK
  // ===========================================================================
  {
    id: 'side_plank',
    name: 'Side plank',
    description: 'Side plank hold: body in one long line, hips lifted, supporting arm straight.',
    category: 'hold',
    qualityThreshold: 65,
    criteria: [
      {
        id: 'body_line',
        label: 'Body line',
        kind: 'segment_vs_horizontal',
        segment: [LM.LEFT_SHOULDER, LM.LEFT_ANKLE],
        target: 0,
        tolerance: 18,
        falloff: 40,
        weight: 35,
        feedbackHigh: 'Lift hips into one long line ({delta}°).',
      },
      {
        id: 'support_elbow',
        label: 'Support arm straight',
        kind: 'joint_angle',
        points: L_ELBOW,
        targetMin: 155,
        targetMax: 180,
        tolerance: 10,
        weight: 25,
        feedbackLow: 'Straighten the supporting arm.',
      },
      {
        id: 'hips',
        label: 'Hips open',
        kind: 'joint_angle',
        points: L_HIP,
        targetMin: 150,
        targetMax: 180,
        tolerance: 12,
        weight: 25,
        feedbackLow: 'Open / lift the hips.',
      },
      {
        id: 'knees',
        label: 'Knees straight',
        kind: 'joint_angle',
        points: L_KNEE,
        targetMin: 155,
        targetMax: 180,
        tolerance: 10,
        weight: 15,
        feedbackLow: 'Straighten knees.',
      },
    ],
  },

  // ===========================================================================
  // ARM POSITIONS (lesson) — standing, then reused on lunges
  // ===========================================================================
  {
    id: 'arms_low_v_back',
    name: 'Arms: low V (back)',
    description: 'Standing low V with the arms reaching slightly back.',
    bodyPosition:
      'Feet together, tall stand. Arms reach down and slightly back in a low V — not covering the ears, not a T. Elbows straight. Chest stays lifted.',
    category: 'static',
    qualityThreshold: 60,
    cameraView: 'side',
    tips: ['Side view so we can see the arms going back.', 'Keep elbows straight.'],
    criteria: [
      {
        id: 'elbows',
        label: 'Elbows straight',
        kind: 'joint_angle',
        points: L_ELBOW,
        targetMin: 155,
        targetMax: 180,
        tolerance: 10,
        weight: 25,
        feedbackLow: 'Straighten elbows.',
      },
      {
        id: 'low_v',
        label: 'Low V (not overhead)',
        kind: 'joint_angle',
        points: L_SHOULDER,
        targetMin: 20,
        targetMax: 80,
        tolerance: 15,
        falloff: 40,
        weight: 40,
        feedbackLow: 'Drop the arms into a low V.',
        feedbackHigh: 'Keep the V low — not up by the ears.',
      },
      {
        id: 'torso',
        label: 'Torso tall',
        kind: 'segment_vs_vertical',
        segment: [LM.LEFT_HIP, LM.LEFT_SHOULDER],
        target: 0,
        tolerance: 18,
        falloff: 40,
        weight: 20,
        feedbackHigh: 'Stand taller.',
      },
      {
        id: 'feet_together',
        label: 'Feet together',
        kind: 'point_distance',
        pair: [LM.LEFT_ANKLE, LM.RIGHT_ANKLE],
        target: 0,
        tolerance: 0.08,
        falloff: 0.2,
        weight: 15,
        feedbackHigh: 'Keep feet together.',
      },
    ],
  },
  {
    id: 'arms_front_middle',
    name: 'Arms: front middle',
    description: 'Arms reach forward at about chest / shoulder height, together in front.',
    bodyPosition:
      'Tall stand. Arms reach straight forward at middle height (not up by the ears, not down by the hips). Elbows straight. Hands together-ish in front of the chest.',
    category: 'static',
    qualityThreshold: 60,
    cameraView: 'side',
    tips: ['Side view shows the forward reach best.'],
    criteria: [
      {
        id: 'forward',
        label: 'Arms forward',
        kind: 'segment_vs_horizontal',
        segment: [LM.LEFT_SHOULDER, LM.LEFT_WRIST],
        target: 0,
        tolerance: 25,
        falloff: 45,
        weight: 40,
        needsView: 'side',
        feedbackHigh: 'Reach arms forward at middle height ({delta}°).',
      },
      {
        id: 'elbows',
        label: 'Elbows straight',
        kind: 'joint_angle',
        points: L_ELBOW,
        targetMin: 155,
        targetMax: 180,
        tolerance: 10,
        weight: 30,
        feedbackLow: 'Straighten elbows.',
      },
      {
        id: 'torso',
        label: 'Torso tall',
        kind: 'segment_vs_vertical',
        segment: [LM.LEFT_HIP, LM.LEFT_SHOULDER],
        target: 0,
        tolerance: 18,
        falloff: 40,
        weight: 30,
        feedbackHigh: 'Keep the chest up.',
      },
    ],
  },
  {
    id: 'arms_open_shoulders',
    name: 'Arms: open shoulders',
    description: 'Same overhead line as FTOS — arms covering ears, hands to the ceiling.',
    bodyPosition:
      'Arms by the ears, elbows straight, shoulders fully open, hands reaching to the ceiling. This is the same arm line used in FTOS, lunge, lever, and handstand.',
    category: 'static',
    qualityThreshold: 65,
    cameraView: 'any',
    tips: ['Any facing. Cover the ears.'],
    criteria: [
      {
        id: 'shoulders',
        label: 'Open shoulders',
        kind: 'joint_angle',
        points: L_SHOULDER,
        targetMin: 150,
        targetMax: 180,
        tolerance: 10,
        weight: 45,
        feedbackLow: 'Open shoulders — arms by ears.',
      },
      {
        id: 'elbows',
        label: 'Elbows straight',
        kind: 'joint_angle',
        points: L_ELBOW,
        targetMin: 160,
        targetMax: 180,
        tolerance: 8,
        weight: 35,
        feedbackLow: 'Straighten elbows.',
      },
      {
        id: 'torso',
        label: 'Torso tall',
        kind: 'segment_vs_vertical',
        segment: [LM.LEFT_HIP, LM.LEFT_SHOULDER],
        target: 0,
        tolerance: 15,
        falloff: 40,
        weight: 20,
        feedbackHigh: 'Stand taller.',
      },
    ],
  },
  {
    id: 'arms_t',
    name: 'Arms: T',
    description: 'Arms straight out to the sides at shoulder height — a letter T.',
    bodyPosition:
      'Face the camera. Arms reach straight out to both sides at shoulder height, elbows locked, wrists in line with the shoulders. Chest lifted. This is a T, not a high V and not overhead.',
    category: 'static',
    qualityThreshold: 60,
    cameraView: 'front',
    tips: ['FACE THE CAMERA so both arms show in the T.'],
    criteria: [
      {
        id: 'left_t',
        label: 'Left arm T',
        kind: 'segment_vs_horizontal',
        segment: [LM.LEFT_SHOULDER, LM.LEFT_WRIST],
        target: 0,
        tolerance: 20,
        falloff: 45,
        weight: 30,
        needsView: 'front',
        feedbackHigh: 'Left arm out to the side at shoulder height.',
      },
      {
        id: 'right_t',
        label: 'Right arm T',
        kind: 'segment_vs_horizontal',
        segment: [LM.RIGHT_SHOULDER, LM.RIGHT_WRIST],
        target: 0,
        tolerance: 20,
        falloff: 45,
        weight: 30,
        needsView: 'front',
        feedbackHigh: 'Right arm out to the side at shoulder height.',
      },
      {
        id: 'elbows',
        label: 'Elbows straight',
        kind: 'composite_min',
        of: ['_t_l_elb', '_t_r_elb'],
        tolerance: 0,
        weight: 25,
      },
      {
        id: '_t_l_elb',
        label: 'L elbow',
        kind: 'joint_angle',
        points: L_ELBOW,
        targetMin: 155,
        targetMax: 180,
        tolerance: 10,
        weight: 1,
        feedbackLow: 'Straighten left elbow.',
      },
      {
        id: '_t_r_elb',
        label: 'R elbow',
        kind: 'joint_angle',
        points: R_ELBOW,
        targetMin: 155,
        targetMax: 180,
        tolerance: 10,
        weight: 1,
        feedbackLow: 'Straighten right elbow.',
      },
      {
        id: 'torso',
        label: 'Torso tall',
        kind: 'segment_vs_vertical',
        segment: [LM.LEFT_HIP, LM.LEFT_SHOULDER],
        target: 0,
        tolerance: 15,
        falloff: 40,
        weight: 15,
        feedbackHigh: 'Stand taller.',
      },
    ],
  },
  {
    id: 'arms_high_v_chest',
    name: 'Arms: high V, chest out',
    description: 'High V arms with the chest open — not covering the ears yet.',
    bodyPosition:
      'Arms lift into a high V (wider than covering the ears). Chest is proud / open. Elbows straight. Head stays up. This is not FTOS — the arms stay in a V.',
    category: 'static',
    qualityThreshold: 60,
    cameraView: 'front',
    tips: ['Face the camera. Chest out. High V, not arms by ears.'],
    criteria: [
      {
        id: 'high_v',
        label: 'High V (not by ears)',
        kind: 'joint_angle',
        points: L_SHOULDER,
        targetMin: 90,
        targetMax: 145,
        tolerance: 12,
        falloff: 40,
        weight: 40,
        feedbackLow: 'Lift arms into a high V.',
        feedbackHigh: 'Keep a V — don’t cover the ears yet.',
      },
      {
        id: 'elbows',
        label: 'Elbows straight',
        kind: 'joint_angle',
        points: L_ELBOW,
        targetMin: 155,
        targetMax: 180,
        tolerance: 10,
        weight: 25,
        feedbackLow: 'Straighten elbows.',
      },
      {
        id: 'chest',
        label: 'Chest open / tall',
        kind: 'segment_vs_vertical',
        segment: [LM.LEFT_HIP, LM.LEFT_SHOULDER],
        target: 0,
        tolerance: 18,
        falloff: 40,
        weight: 35,
        feedbackHigh: 'Chest out — stand taller.',
      },
    ],
  },

  // Lunge arm-position holds use LANDING lunge legs: shorter stance, back heel FLAT.
  {
    id: 'lunge_arms_low_v',
    name: 'Lunge · low V arms',
    description: 'Landing-lunge legs with low V arms back. Back heel flat, shorter stance.',
    bodyPosition:
      'Same stance as the landing lunge: front knee bent, back leg straight, back HEEL FLAT, feet closer than a starting lunge. Arms in a low V slightly back. Side view.',
    category: 'hold',
    qualityThreshold: 60,
    cameraView: 'side',
    stanceAware: true,
    tips: ['Side view. Back heel flat. Shorter than a starting lunge. Arms low V, not overhead.'],
    criteria: [
      {
        id: 'front_knee',
        label: 'Front knee',
        kind: 'joint_angle',
        points: L_KNEE,
        targetMin: 85,
        targetMax: 125,
        tolerance: 12,
        weight: 18,
        feedbackLow: 'Bend front knee more.',
        feedbackHigh: 'Ease front knee bend.',
      },
      {
        id: 'back_leg',
        label: 'Back leg straight',
        kind: 'joint_angle',
        points: R_KNEE,
        targetMin: 155,
        targetMax: 180,
        tolerance: 10,
        weight: 20,
        feedbackLow: 'Straighten the back leg.',
      },
      LANDING_HEEL_FLAT,
      LANDING_CLOSER_STEP,
      {
        id: 'low_v',
        label: 'Low V arms',
        kind: 'joint_angle',
        points: L_SHOULDER,
        targetMin: 20,
        targetMax: 85,
        tolerance: 15,
        weight: 34,
        feedbackLow: 'Drop arms into a low V.',
        feedbackHigh: 'Keep the V low — not by the ears.',
      },
      {
        id: 'elbows',
        label: 'Elbows straight',
        kind: 'joint_angle',
        points: L_ELBOW,
        targetMin: 155,
        targetMax: 180,
        tolerance: 10,
        weight: 16,
        feedbackLow: 'Straighten elbows.',
      },
    ],
  },
  {
    id: 'lunge_arms_front',
    name: 'Lunge · arms front middle',
    description: 'Landing-lunge legs with arms reaching forward at middle height. Back heel flat.',
    bodyPosition:
      'Same stance as the landing lunge: back leg straight, back HEEL FLAT, feet closer than a starting lunge. Arms reach forward at chest height, elbows straight.',
    category: 'hold',
    qualityThreshold: 60,
    cameraView: 'side',
    stanceAware: true,
    tips: ['Side view. Back heel flat. Shorter than a starting lunge. Arms forward, not up.'],
    criteria: [
      {
        id: 'front_knee',
        label: 'Front knee',
        kind: 'joint_angle',
        points: L_KNEE,
        targetMin: 85,
        targetMax: 125,
        tolerance: 12,
        weight: 18,
        feedbackLow: 'Bend front knee more.',
        feedbackHigh: 'Ease front knee bend.',
      },
      {
        id: 'back_leg',
        label: 'Back leg straight',
        kind: 'joint_angle',
        points: R_KNEE,
        targetMin: 155,
        targetMax: 180,
        tolerance: 10,
        weight: 20,
        feedbackLow: 'Straighten the back leg.',
      },
      LANDING_HEEL_FLAT,
      LANDING_CLOSER_STEP,
      {
        id: 'forward',
        label: 'Arms forward',
        kind: 'segment_vs_horizontal',
        segment: [LM.LEFT_SHOULDER, LM.LEFT_WRIST],
        target: 0,
        tolerance: 25,
        falloff: 45,
        weight: 34,
        needsView: 'side',
        feedbackHigh: 'Reach arms forward at middle height.',
      },
      {
        id: 'elbows',
        label: 'Elbows straight',
        kind: 'joint_angle',
        points: L_ELBOW,
        targetMin: 155,
        targetMax: 180,
        tolerance: 10,
        weight: 20,
        feedbackLow: 'Straighten elbows.',
      },
    ],
  },
  {
    id: 'lunge_arms_open',
    name: 'Lunge · open shoulders',
    description: 'Landing-lunge legs with FTOS arms (by the ears). Back heel flat, shorter stance.',
    bodyPosition:
      'Same stance as the landing lunge: front knee bent, back leg straight, back HEEL FLAT, feet closer than a starting lunge. Arms covering the ears, shoulders open.',
    category: 'hold',
    qualityThreshold: 65,
    cameraView: 'side',
    stanceAware: true,
    tips: ['Open-shoulder arms on a landing lunge. Back heel flat. Shorter than a starting lunge.'],
    criteria: [
      {
        id: 'front_knee',
        label: 'Front knee',
        kind: 'joint_angle',
        points: L_KNEE,
        targetMin: 85,
        targetMax: 125,
        tolerance: 12,
        weight: 16,
        feedbackLow: 'Bend front knee more.',
        feedbackHigh: 'Ease front knee bend.',
      },
      LUNGE_BACK_LEG,
      LANDING_HEEL_FLAT,
      LANDING_CLOSER_STEP,
      { ...LUNGE_OPEN_SHOULDERS, weight: 24 },
      LUNGE_DIAGONAL,
      LUNGE_STRAIGHT_BACK,
      {
        id: 'elbows',
        label: 'Elbows straight',
        kind: 'joint_angle',
        points: L_ELBOW,
        targetMin: 160,
        targetMax: 180,
        tolerance: 8,
        weight: 10,
        feedbackLow: 'Straighten elbows.',
      },
    ],
  },
  {
    id: 'lunge_arms_t',
    name: 'Lunge · T arms',
    description:
      'Landing-lunge legs with arms in a T. Face the camera so both arms show. Back heel flat.',
    bodyPosition:
      'Same stance as the landing lunge (back leg straight, back HEEL FLAT, shorter than a starting lunge) with arms straight out to the sides at shoulder height. Face the camera.',
    category: 'hold',
    qualityThreshold: 60,
    cameraView: 'front',
    stanceAware: true,
    tips: ['FACE THE CAMERA for the T. Back heel flat. Shorter than a starting lunge. Back leg still straight.'],
    criteria: [
      {
        id: 'front_knee',
        label: 'Front knee',
        kind: 'joint_angle',
        points: L_KNEE,
        targetMin: 85,
        targetMax: 125,
        tolerance: 12,
        weight: 18,
        feedbackLow: 'Bend front knee more.',
        feedbackHigh: 'Ease front knee bend.',
      },
      {
        id: 'back_leg',
        label: 'Back leg straight',
        kind: 'joint_angle',
        points: R_KNEE,
        targetMin: 155,
        targetMax: 180,
        tolerance: 10,
        weight: 18,
        feedbackLow: 'Straighten the back leg.',
      },
      LANDING_HEEL_FLAT,
      LANDING_CLOSER_STEP,
      {
        id: 'left_t',
        label: 'Left arm T',
        kind: 'segment_vs_horizontal',
        segment: [LM.LEFT_SHOULDER, LM.LEFT_WRIST],
        target: 0,
        tolerance: 22,
        falloff: 45,
        weight: 22,
        needsView: 'front',
        feedbackHigh: 'Left arm out to the side.',
      },
      {
        id: 'right_t',
        label: 'Right arm T',
        kind: 'segment_vs_horizontal',
        segment: [LM.RIGHT_SHOULDER, LM.RIGHT_WRIST],
        target: 0,
        tolerance: 22,
        falloff: 45,
        weight: 22,
        needsView: 'front',
        feedbackHigh: 'Right arm out to the side.',
      },
      {
        id: 'elbows',
        label: 'Elbows straight',
        kind: 'joint_angle',
        points: L_ELBOW,
        targetMin: 155,
        targetMax: 180,
        tolerance: 10,
        weight: 12,
        feedbackLow: 'Straighten elbows.',
      },
    ],
  },
  {
    id: 'lunge_arms_high_v',
    name: 'Lunge · high V chest out',
    description: 'Landing-lunge legs with a high V and an open chest. Back heel flat, shorter stance.',
    bodyPosition:
      'Same stance as the landing lunge: back leg straight, back HEEL FLAT, feet closer than a starting lunge. Arms in a high V (not covering the ears). Chest open.',
    category: 'hold',
    qualityThreshold: 60,
    cameraView: 'any',
    stanceAware: true,
    tips: ['High V, chest out — not arms by ears yet. Back heel flat. Shorter than a starting lunge.'],
    criteria: [
      {
        id: 'front_knee',
        label: 'Front knee',
        kind: 'joint_angle',
        points: L_KNEE,
        targetMin: 85,
        targetMax: 125,
        tolerance: 12,
        weight: 18,
        feedbackLow: 'Bend front knee more.',
        feedbackHigh: 'Ease front knee bend.',
      },
      {
        id: 'back_leg',
        label: 'Back leg straight',
        kind: 'joint_angle',
        points: R_KNEE,
        targetMin: 155,
        targetMax: 180,
        tolerance: 10,
        weight: 20,
        feedbackLow: 'Straighten the back leg.',
      },
      LANDING_HEEL_FLAT,
      LANDING_CLOSER_STEP,
      {
        id: 'high_v',
        label: 'High V',
        kind: 'joint_angle',
        points: L_SHOULDER,
        targetMin: 90,
        targetMax: 145,
        tolerance: 12,
        weight: 34,
        feedbackLow: 'Lift arms into a high V.',
        feedbackHigh: 'Keep a V — don’t cover the ears yet.',
      },
      {
        id: 'elbows',
        label: 'Elbows straight',
        kind: 'joint_angle',
        points: L_ELBOW,
        targetMin: 155,
        targetMax: 180,
        tolerance: 10,
        weight: 20,
        feedbackLow: 'Straighten elbows.',
      },
    ],
  },
]

/** Fast lookup by id */
export const SHAPES_BY_ID: Record<string, ShapeDef> = Object.fromEntries(
  SHAPES.map((s) => [s.id, s]),
)

export function getShape(id: string): ShapeDef | undefined {
  if (id === 'hollow') return SHAPES_BY_ID.hollow_arms_up
  return SHAPES_BY_ID[id]
}
