/**
 * Starting skill-path map. Coaches add and edit more in the app.
 * Required = usually needed. Helpful = makes the goal more likely.
 * Alt = another order that can come first.
 */

import type { ConditioningNeed, SkillDef, SkillNeed } from '../lib/skillPaths'

const now = '2026-09-13T00:00:00.000Z'

export const SHIPPED_SKILLS: SkillDef[] = [
  {
    id: 'skl_ro_bhs_tuck',
    name: 'Round-off handspring back tuck',
    aliases: ['RO BHS tuck', 'round off back handspring tuck'],
    note: 'Name the surface. Floor and dead mat need a series that speeds up and a handspring that can rebound.',
    surfaces: ['spring_floor', 'dead_mat', 'tramp', 'tumble_trak', 'rod_airfloor'],
    createdAt: now,
    updatedAt: now,
    shipped: true,
  },
  {
    id: 'skl_ro_bhs_full',
    name: 'Round-off handspring full twisting layout',
    aliases: ['RO BHS full', 'round off back handspring full'],
    note: 'Layout shape deadline and a tramp full come before expecting this on floor.',
    surfaces: ['spring_floor', 'dead_mat', 'tramp', 'tumble_trak'],
    createdAt: now,
    updatedAt: now,
    shipped: true,
  },
  {
    id: 'skl_standing_tuck',
    name: 'Standing back tuck',
    aliases: ['standing tuck'],
    note: 'Athletes can get this before a running tuck. Work it from more power down to less power.',
    surfaces: ['tramp', 'tumble_trak', 'rod_airfloor', 'spring_floor', 'dead_mat'],
    powerDown: [
      { id: 'pd_tuck_2step', label: '2-step hurdle' },
      { id: 'pd_tuck_power', label: 'Power hurdle' },
      { id: 'pd_tuck_hop', label: 'Passé hop' },
      { id: 'pd_tuck_fall', label: 'Passé fall' },
      { id: 'pd_tuck_3', label: 'Standing 3' },
      { id: 'pd_tuck_2', label: 'Standing 2' },
      { id: 'pd_tuck_stand', label: 'Standing tuck' },
    ],
    createdAt: now,
    updatedAt: now,
    shipped: true,
  },
  {
    id: 'skl_standing_layout',
    name: 'Standing layout',
    aliases: ['standing lay'],
    note: 'Same more-power-to-less-power path as the standing tuck.',
    surfaces: ['tramp', 'tumble_trak', 'rod_airfloor', 'spring_floor'],
    powerDown: [
      { id: 'pd_lay_2step', label: '2-step hurdle' },
      { id: 'pd_lay_power', label: 'Power hurdle' },
      { id: 'pd_lay_hop', label: 'Passé hop' },
      { id: 'pd_lay_fall', label: 'Passé fall' },
      { id: 'pd_lay_3', label: 'Standing 3' },
      { id: 'pd_lay_2', label: 'Standing 2' },
      { id: 'pd_lay_stand', label: 'Standing layout' },
    ],
    createdAt: now,
    updatedAt: now,
    shipped: true,
  },
  {
    id: 'skl_standing_full',
    name: 'Standing full',
    aliases: ['standing full twist'],
    note: 'Same power-down idea as tuck and layout. Pair with the open tuck and a tuck up a raised surface.',
    surfaces: ['tramp', 'tumble_trak', 'rod_airfloor', 'spring_floor'],
    powerDown: [
      { id: 'pd_full_2step', label: '2-step hurdle' },
      { id: 'pd_full_power', label: 'Power hurdle' },
      { id: 'pd_full_hop', label: 'Passé hop' },
      { id: 'pd_full_fall', label: 'Passé fall' },
      { id: 'pd_full_3', label: 'Standing 3' },
      { id: 'pd_full_2', label: 'Standing 2' },
      { id: 'pd_full_stand', label: 'Standing full' },
    ],
    createdAt: now,
    updatedAt: now,
    shipped: true,
  },
  {
    id: 'skl_standing_double',
    name: 'Standing double',
    aliases: ['standing double back'],
    note: 'Same more-power-to-less-power process. Add the pieces as you learn them.',
    surfaces: ['tramp', 'tumble_trak'],
    powerDown: [
      { id: 'pd_dbl_2step', label: '2-step hurdle' },
      { id: 'pd_dbl_power', label: 'Power hurdle' },
      { id: 'pd_dbl_hop', label: 'Passé hop' },
      { id: 'pd_dbl_fall', label: 'Passé fall' },
      { id: 'pd_dbl_3', label: 'Standing 3' },
      { id: 'pd_dbl_2', label: 'Standing 2' },
      { id: 'pd_dbl_stand', label: 'Standing double' },
    ],
    createdAt: now,
    updatedAt: now,
    shipped: true,
  },
  {
    id: 'skl_layout',
    name: 'Layout',
    aliases: ['lay', 'straight layout'],
    note: 'A good layout needs a real hollow with arms up. Name the surface.',
    surfaces: ['tramp', 'tumble_trak', 'rod_airfloor', 'spring_floor', 'dead_mat'],
    createdAt: now,
    updatedAt: now,
    shipped: true,
  },
  {
    id: 'skl_ro_bhs_series',
    name: 'Round-off back handspring series',
    aliases: ['RO BHS series'],
    note: 'Quality series that speeds up — not just making it to the end.',
    surfaces: ['spring_floor', 'dead_mat', 'tumble_trak', 'rod_airfloor'],
    createdAt: now,
    updatedAt: now,
    shipped: true,
  },
  {
    id: 'skl_ro_bhs_rebound',
    name: 'Round-off handspring that can rebound',
    aliases: ['RO HS rebound'],
    note: 'A handspring that can genuinely rebound, not just finish.',
    surfaces: ['spring_floor', 'dead_mat', 'tumble_trak', 'rod_airfloor'],
    createdAt: now,
    updatedAt: now,
    shipped: true,
  },
  {
    id: 'skl_tramp_tuck_from_hs',
    name: 'Back tuck on tramp from a handspring or round-off',
    aliases: ['tramp tuck from BHS'],
    note: 'Head in. Hit tuck by the first quarter of the flip.',
    surfaces: ['tramp'],
    createdAt: now,
    updatedAt: now,
    shipped: true,
  },
  {
    id: 'skl_tramp_bounce_tuck',
    name: 'Standalone back tuck from bounces on tramp',
    aliases: ['bounce tuck'],
    note: 'Quality tuck from bounces — not only from a handspring.',
    surfaces: ['tramp'],
    createdAt: now,
    updatedAt: now,
    shipped: true,
  },
  {
    id: 'skl_tramp_full',
    name: 'Full on trampoline',
    aliases: ['tramp full'],
    surfaces: ['tramp'],
    createdAt: now,
    updatedAt: now,
    shipped: true,
  },
  {
    id: 'skl_standing_open_tuck',
    name: 'Standing open tuck',
    aliases: ['open tuck'],
    surfaces: ['tramp', 'tumble_trak', 'rod_airfloor', 'spring_floor'],
    createdAt: now,
    updatedAt: now,
    shipped: true,
  },
  {
    id: 'skl_tuck_up_raised',
    name: 'Back tuck up a knee-high raised surface',
    aliases: ['tuck up a box'],
    note: 'Standing back tuck that lands on something about knee height.',
    surfaces: ['tramp', 'tumble_trak', 'spring_floor'],
    createdAt: now,
    updatedAt: now,
    shipped: true,
  },
  {
    id: 'skl_ro_bhs',
    name: 'Round-off back handspring',
    aliases: ['RO BHS'],
    note: 'An athlete can get a standing back handspring first, or this first. Neither is the only order.',
    surfaces: ['spring_floor', 'dead_mat', 'tumble_trak', 'rod_airfloor'],
    createdAt: now,
    updatedAt: now,
    shipped: true,
  },
  {
    id: 'skl_standing_bhs',
    name: 'Standing back handspring',
    aliases: ['standing BHS'],
    note: 'Can come before a round-off handspring, or after.',
    surfaces: ['spring_floor', 'dead_mat', 'tumble_trak', 'rod_airfloor', 'tramp'],
    createdAt: now,
    updatedAt: now,
    shipped: true,
  },
]

export const SHIPPED_NEEDS: SkillNeed[] = [
  {
    id: 'need_tuck_series',
    skillId: 'skl_ro_bhs_tuck',
    needSkillId: 'skl_ro_bhs_series',
    kind: 'required',
    note: 'A quality series that speeds up. Start here when they named a floor or dead-mat tuck.',
    surfaces: ['spring_floor', 'dead_mat'],
    order: 10,
    shipped: true,
  },
  {
    id: 'need_tuck_rebound',
    skillId: 'skl_ro_bhs_tuck',
    needSkillId: 'skl_ro_bhs_rebound',
    kind: 'required',
    note: 'The handspring has to be able to genuinely rebound.',
    surfaces: ['spring_floor', 'dead_mat'],
    order: 20,
    shipped: true,
  },
  {
    id: 'need_tuck_tramp_hs',
    skillId: 'skl_ro_bhs_tuck',
    needSkillId: 'skl_tramp_tuck_from_hs',
    kind: 'helpful',
    note: 'Head in, tuck by first quarter, from a standing handspring or round-off on tramp.',
    surfaces: ['tramp', 'spring_floor', 'dead_mat'],
    order: 30,
    shipped: true,
  },
  {
    id: 'need_tuck_bounce',
    skillId: 'skl_ro_bhs_tuck',
    needSkillId: 'skl_tramp_bounce_tuck',
    kind: 'helpful',
    note: 'A clean standalone bounce tuck on tramp.',
    surfaces: ['tramp', 'spring_floor', 'dead_mat'],
    order: 40,
    shipped: true,
  },
  {
    id: 'need_full_layout',
    skillId: 'skl_ro_bhs_full',
    needSkillId: 'skl_layout',
    kind: 'required',
    note: 'A straight layout that hits a good shape deadline.',
    order: 10,
    shipped: true,
  },
  {
    id: 'need_full_tramp',
    skillId: 'skl_ro_bhs_full',
    needSkillId: 'skl_tramp_full',
    kind: 'helpful',
    note: 'A full on trampoline before expecting it from a series on floor.',
    order: 20,
    shipped: true,
  },
  {
    id: 'need_stand_ro_tuck',
    skillId: 'skl_standing_tuck',
    needSkillId: 'skl_ro_bhs_tuck',
    kind: 'helpful',
    note: 'A good running tuck helps, but a standing tuck can come first.',
    order: 10,
    shipped: true,
  },
  {
    id: 'need_sfull_open',
    skillId: 'skl_standing_full',
    needSkillId: 'skl_standing_open_tuck',
    kind: 'required',
    note: 'Standing open tuck before expecting a standing full.',
    order: 10,
    shipped: true,
  },
  {
    id: 'need_sfull_box',
    skillId: 'skl_standing_full',
    needSkillId: 'skl_tuck_up_raised',
    kind: 'required',
    note: 'Back tuck up a knee-high raised surface.',
    order: 20,
    shipped: true,
  },
  {
    id: 'need_ro_or_stand',
    skillId: 'skl_ro_bhs',
    needSkillId: 'skl_standing_bhs',
    kind: 'alt',
    note: 'Standing back handspring can come first — or the other way around.',
    order: 10,
    shipped: true,
  },
]

export const SHIPPED_CONDITIONING: ConditioningNeed[] = [
  {
    id: 'cnd_layout_hollow',
    skillId: 'skl_layout',
    label: 'Hold a proper hollow, arms up, for one minute',
    kind: 'required',
    shapeId: 'hollow',
    note: 'For an athlete to expect a good layout.',
    shipped: true,
  },
  {
    id: 'cnd_full_hollow',
    skillId: 'skl_ro_bhs_full',
    label: 'Hold a proper hollow, arms up, for one minute',
    kind: 'helpful',
    shapeId: 'hollow',
    shipped: true,
  },
]
